### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by rainymoon911** [NARKOZ/gitlab#101]
Hi

the gitlab cli worked well before , but totay it has errors,like this

        root@gitlab ~# gitlab users
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
I didn't change everything, but why?(the gitlab self works well and the verision of cli is the latest)

**Comment by mcandre** [comment]
@rainymoon911 Were you able to fix the problem? What steps did you take?
