### ISSUE TITLE
Support "search" api calls

### ISSUE THREAD

**Issue by StephenOTT** [NARKOZ/gitlab#105]
The latest api for gitlab has many need for using search to find information.  such as: get projects/search/:query

**Comment by StephenOTT** [comment]
would be nice if there was support for the various search features such as:

![screen shot 2015-01-25 at 8 58 58 pm](https://cloud.githubusercontent.com/assets/1994838/5894430/0979af4a-a4d5-11e4-99d4-69f33a7521dd.png)

**Comment by asedge** [comment]
The `projects` method can be used for searching and supports all the same options:
```
2.2.0 :027 > Gitlab.projects(search: 'proj').map { |p| p.name }                                                                                                                                                           
 => ["proj1", "proj2"] 
2.2.0 :028 > Gitlab.projects(search: 'proj', order_by: 'name', sort: 'desc').map { |p| p.name }
 => ["proj2", "proj1"] 
2.2.0 :029 > Gitlab.projects(search: 'proj', order_by: 'name', sort: 'asc', per_page: 1).map { |p| p.name }
 => ["proj1"] 
```

**Comment by asedge** [comment]
Reopen if this needs further discussion.  Thanks!

**Comment by StephenOTT** [comment]
Thanks!

**Comment by StephenOTT** [comment]
@asedge 
Can you show an example with Namespace/Project ?
I am getting varying results and just trying to hunt down the issue.

**Comment by asedge** [comment]
@StephenOTT Looking at the definition of the search method (here: https://github.com/gitlabhq/gitlabhq/blob/master/app/models/project.rb#L200-L207) you probably won't be able to search like 'Namespace/Project'.  Just one or the other.  Once you get the results back you could always use the `reject` method to filter further.

**Comment by StephenOTT** [comment]
@asedge is there a restriction on being able to search all of GitLab?  I seem to only be able to return projects that I am the owner of.  I cannot seem to do a search through all public repos or private repos that i can see... ?

Thanks
