### ISSUE TITLE
gitlab help

### ISSUE THREAD

**Issue by cudos** [NARKOZ/gitlab#106]
Using Gitlab Ruby Gem 3.3.0: The outpout of "gitlab help" is formatted non-standard, filling too much vertical space (nearly two screens). A tool with an unreadable help like this is quite unusable.

**Comment by jvanbaarsen** [comment]
We will look into this. In the meanwhile, we do accept PR's that will better this!

**Comment by NARKOZ** [comment]
An easy way to fix that is to split help into several small tables, so each table will contain max 3 rows.

**Comment by asedge** [comment]
I split the help into 2 smaller tables.  One contains help topics (Branches, Users, etc) and the other will contain only commands under a specific topic (protect_branch, branches, create_branch, etc.).  See this gist: https://gist.github.com/asedge/1494a79e2429f42c76cf

Feedback would be appreciated.

**Comment by asedge** [comment]
@cudos @NARKOZ Any feedback on the gist I posted?

**Comment by NARKOZ** [comment]
@asedge LGTM :+1:

**Comment by asedge** [comment]
@NARKOZ Cool, thanks!  I'll merge it in soon.
