### ISSUE TITLE
create merge request from forked project

### ISSUE THREAD

**Issue by logicminds** [NARKOZ/gitlab#108]
Github calls these types pull requests, but gitlab calls them merge requests.  But basically its a merge request from a forked project onto the origin project.  Its a pretty common workflow.  However there doesn't seem to be a way to do this with the gitlab code.  I think all that is needed it so specify the destination project as well as the destination branch.

https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/merge_requests.rb#L46

It looks like its possible:

https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/merge_requests.md#create-mr

**Comment by asedge** [comment]
You just need to specify `:target_project_id` along with the other options.  This worked for me:
```
Gitlab.create_merge_request(72, "New MR", source_branch: 'some_feature', target_branch: 'master', target_project_id: 71)
```
The documentation for this method needs an update though - thanks for pointing that out.  I'll take care of that shortly.
