### ISSUE TITLE
Get issues for milestone

### ISSUE THREAD

**Issue by pbendersky** [NARKOZ/gitlab#114]
GitLab has an API point to get all issues from a given milestone.

`GET /projects/:id/milestones/:milestone_id/issues`

I want to send a PR with this addition, but wanted to discuss first what's the best place to implement it without breaking the library's API. The `issues` method in https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/issues.rb#L17-L23 receives a project parameter, but not a milestone.

Should I add a `milestone_issues` method that gets a project and milestone parameter?

**Comment by NARKOZ** [comment]
> Should I add a `milestone_issues` method that gets a project and milestone parameter?

Yes, the method should be added to https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/milestones.rb

**Comment by asedge** [comment]
@pbendersky If your commit message includes "closes|fixes #<issue_id>" it will automatically close the issue when we merge it.  Just in case you didn't know. Thanks again! :+1:

**Comment by pbendersky** [comment]
Forgot about it, sorry. :)
