### ISSUE TITLE
Missing `to_s` method for `ObjectifiedHash`

### ISSUE THREAD

**Issue by deric** [NARKOZ/gitlab#121]
`Objec` doesn't have correct `to_s` nor `inspect` method. Anyway, what's the purpose of the class? You could have used Ruby's `OpenStruct`, right? It does pretty much the same.

http://www.opensource.apple.com/source/ruby/ruby-83.4/ruby/lib/ostruct.rb

**Comment by NARKOZ** [comment]
[`Gitlab::ObjectifiedHash`](https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/objectified_hash.rb) converts hashes to the objects. 

There is `to_h` (`to_hash`) method which allows you to access the original hash. And `inspect` was method just added.

There are many reasons why I didn't use openstruct, and the one of them is that openstruct doesn't handle nested hashes.
