### ISSUE TITLE
:Page and :Per_Page are not available for Notes/Comments

### ISSUE THREAD

**Issue by StephenOTT** [NARKOZ/gitlab#125]
Looking over the Notes/Comments API i am seeing that there is not parameter options for `:Page` and `:Per_Page`.  Was this done on purpose?
THanks

**Comment by StephenOTT** [comment]
Pagination on: http://doc.gitlab.com/ce/api/README.html#pagination does not say there is a exception for Notes/Comments.  Any insights?

**Comment by NARKOZ** [comment]
Pull request is welcome.

**Comment by AnneshaChowdhury** [comment]
Hi,
Is there a :per_page query for getting the project events too? For my application, I am getting lot of Internal Server Errors for some pages , and if we reduce the events per page, the errors are getting reduced.

When I add that as an parameter, it gives me an error saying that more than 2 arguments are not supported .

The other two arguments are date-limit and obviously the project-id.

Would appreciate some input on this?

**Comment by NARKOZ** [comment]
@AnneshaChowdhury no, GitLab API doesn't support that https://docs.gitlab.com/ce/api/events.html#list-a-project-s-visible-events
