### ISSUE TITLE
How to set ENV for httparty to indicate self-signed cert in CLI mode?

### ISSUE THREAD

**Issue by xied75** [NARKOZ/gitlab#127]
Dear all,

It seems in the code we are only handling API_ENDPOINT and API_SECRET, there is no where handling httparty settings from the ENV?

(We have a gitlab using self-signed certs. And I'm using this tool as CLI to manage my snippets, just for the record.)

Best,

Dong

**Comment by NARKOZ** [comment]
I'm afraid it's not possible at the moment. Pull request is welcome.

**Comment by asedge** [comment]
@xied75 I don't have a Gitlab server using self-signed certificates, would you mind testing the commit I pushed (linked above)?  It would be something like:
```
export GITLAB_API_HTTPARTY_OPTIONS="{verify: false}"
```

**Comment by xied75** [comment]
Tried this, still getting same error.

```
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

**Comment by asedge** [comment]
I see the problem, HTTParty expects hash keys to be symbols.

@xied75 I have a file full of exports that I source before using the CLI.

**Comment by asedge** [comment]
@xied75 I pushed another commit to the `load_httparty_from_env` branch on my repo.  I created a self signed cert on my test VM and this worked for me.

**Comment by xied75** [comment]
:+1: 

Happily confirm this is working for me now. Please make this into gem release. :)

**Comment by asedge** [comment]
It will make it in.  Just have been really busy lately.
