### ISSUE TITLE
Where do I put the configuration for gitlab shell?

### ISSUE THREAD

**Issue by atsaloli** [NARKOZ/gitlab#130]
Hello,

Where do I put the ruby code example you've provided so that gitlab shell reads it in when it starts, please?

Aleksey

**Comment by asedge** [comment]
Are you asking how to set the necessary environment variables?

**Comment by atsaloli** [comment]
What environment variables should I set to use gitlab shell?  I need to set
API endpoint.

On Wed, May 13, 2015 at 5:27 PM, Sean Edge <notifications@github.com> wrote:

> Are you asking how to set the necessary environment variables?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NARKOZ/gitlab/issues/130#issuecomment-101863952>.
>



-- 
Need CFEngine training?  Email training@verticalsysadmin.com

**Comment by asedge** [comment]
https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/configuration.rb#L37-L38

**Comment by asedge** [comment]
`GITLAB_API_ENDPOINT` and `GITLAB_API_PRIVATE_TOKEN` are required.  I created some dotfiles in my $HOME directory that export those variables for a couple different instances of Gitlab we run.  Then I just source the one I need.  Reopen this if you need more assistance.
