### ISSUE TITLE
when trying to get a branch by the commit hash it returns 404

### ISSUE THREAD

**Issue by cdub50** [NARKOZ/gitlab#131]
@g.projects.each do |p| 
      @id = p.id if p.name.match(/\test\b/)
    end
    commit = 'ab02cb87eea9887c68d6421448a76a7dcf123456'
    puts @g.commit(@id, commit)

Gitlab::Error::Parsing: The response is not a valid JSON
    /Users/cdub/.rvm/gems/ruby-2.1.5@qa/gems/gitlab-3.3.0/lib/gitlab/request.rb:32:in `rescue in decode'
    /Users/cdub/.rvm/gems/ruby-2.1.5@qa/gems/gitlab-3.3.0/lib/gitlab/request.rb:29:in `decode'
    /Users/cdub/.rvm/gems/ruby-2.1.5@qa/gems/gitlab-3.3.0/lib/gitlab/request.rb:16:in `parse'
    /Users/cdub/.rvm/gems/ruby-2.1.5@qa/gems/gitlab-3.3.0/lib/gitlab/request.rb:10:in `block in <class:Request>'
    /Users/cdub/.rvm/gems/ruby-2.1.5@qa/gems/httparty-0.13.3/lib/httparty/request.rb:309:in `call'
    /Users/cdub/.rvm/gems/ruby-2.1.5@qa/gems/httparty-0.13.3/lib/httparty/request.rb:309:in `parse_response'
    /Users/cdub/.rvm/gems/ruby-2.1.5@qa/gems/httparty-0.13.3/lib/httparty/request.rb:279:in `block in handle_response'
    /Users/cdub/.rvm/gems/ruby-2.1.5@qa/gems/httparty-0.13.3/lib/httparty/response.rb:23:in `call'
    /Users/cdub/.rvm/gems/ruby-2.1.5@qa/gems/httparty-0.13.3/lib/httparty/response.rb:23:in `parsed_response'
    /Users/cdub/.rvm/gems/ruby-2.1.5@qa/gems/gitlab-3.3.0/lib/gitlab/request.rb:109:in `error_message'
    /Users/cdub/.rvm/gems/ruby-2.1.5@qa/gems/gitlab-3.3.0/lib/gitlab/request.rb:67:in `validate'
    /Users/cdub/.rvm/gems/ruby-2.1.5@qa/gems/gitlab-3.3.0/lib/gitlab/request.rb:39:in `get'
    /Users/cdub/.rvm/gems/ruby-2.1.5@qa/gems/gitlab-3.3.0/lib/gitlab/client/repositories.rb:61:in `commit'

**Comment by asedge** [comment]
I think the problem might be your regex.  I'm guessing you mean to match `test<word_boundary>` but the `\t` would match a tab.

**Comment by cdub50** [comment]
even if I put in the id and the hash it still bombs out

**Comment by asedge** [comment]
Try this: `@g.commits(<id>).map(&:id).grep('ab02cb87eea9887c68d6421448a76a7dcf123456')`.  Make sure you replace `<id>` with the id of the project you are searching.  What do you get back?

**Comment by cdub50** [comment]
Seems like that worked does commit just not work? I am trying to get the
branch from the commit.

**Comment by cdub50** [comment]
I only get back the sha hash with the example.

**Comment by asedge** [comment]
The commit method works fine for me.
```
2.1.2 :013 > Gitlab.commit(3,'b8472c8d728badf4b12cb8b59570fa3c54a03bab').message
 => "first commit\n"
```
What version of Gitlab are you running?

**Comment by cdub50** [comment]
6.0.0.rc1

**Comment by asedge** [comment]
I think you may need to update Gitlab.  It looks like the route doesn't exist for getting a single commit in the 6.0.0 release.  https://github.com/gitlabhq/gitlabhq/blob/6-0-stable/lib/api/repositories.rb

**Comment by cdub50** [comment]
Thanks will let our ops team know that we need to update to gain that
functionality.

**Comment by asedge** [comment]
Sure, no problem.  I'm going to close this issue for now.
