### ISSUE TITLE
Installation succeeds, but cli then fails

### ISSUE THREAD

**Issue by TobyHFerguson** [NARKOZ/gitlab#135]
I installed gitlab thus:

```
[root@XXXXX ~]# gem install gitlab
Fetching: terminal-table-1.4.5.gem (100%)
Successfully installed terminal-table-1.4.5
Fetching: multi_xml-0.5.5.gem (100%)
Successfully installed multi_xml-0.5.5
Fetching: httparty-0.13.5.gem (100%)
When you HTTParty, you must party hard!
Successfully installed httparty-0.13.5
Fetching: gitlab-3.4.0.gem (100%)
Successfully installed gitlab-3.4.0
Parsing documentation for terminal-table-1.4.5
Installing ri documentation for terminal-table-1.4.5
Parsing documentation for multi_xml-0.5.5
Installing ri documentation for multi_xml-0.5.5
Parsing documentation for httparty-0.13.5
Installing ri documentation for httparty-0.13.5
Parsing documentation for gitlab-3.4.0
Installing ri documentation for gitlab-3.4.0
Done installing documentation for terminal-table, multi_xml, httparty, gitlab after 3 seconds
4 gems installed
```
But when I attempted to execute the cli I got a failure:
````
[toby.ferguson@XXXX ~]$ export GITLAB_API_ENDPOINT=http://XXXX:8888
[toby.ferguson@XXXX ~]$ export GITLAB_API_PRIVATE_TOKEN='XXXX'
[toby.ferguson@XXXX ~]$ gitlab help
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- readline (LoadError)
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/gitlab-3.4.0/lib/gitlab/shell.rb:5:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/gitlab-3.4.0/lib/gitlab/cli.rb:4:in `require_relative'
	from /usr/local/lib/ruby/gems/2.2.0/gems/gitlab-3.4.0/lib/gitlab/cli.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/gitlab-3.4.0/bin/gitlab:5:in `<top (required)>'
	from /usr/local/bin/gitlab:23:in `load'
	from /usr/local/bin/gitlab:23:in `<main>'
````
My environment:

````
[toby.ferguson@XXXX ~]$ ruby -v; bundle -v; gem -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
-bash: bundle: command not found
2.4.5
````

**Comment by asedge** [comment]
@TobyHFerguson That's strange.  Readline is part of the stdlib that comes with Ruby: http://ruby-doc.org/stdlib-2.2.0/libdoc/readline/rdoc/Readline.html

**Comment by NARKOZ** [comment]
@TobyHFerguson what OS are you using?

**Comment by TobyHFerguson** [comment]
Oracle Linux 6

On Sat, Jun 20, 2015 at 12:44 PM, Nihad Abbasov <notifications@github.com>
wrote:

> @TobyHFerguson <https://github.com/TobyHFerguson> what OS are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NARKOZ/gitlab/issues/135#issuecomment-113812968>.
>



-- 
toby

**Comment by asedge** [comment]
@TobyHFerguson Did you compile ruby yourself or did you install a package from Oracle?  If you compiled it yourself could you share your `./configure`?

**Comment by TobyHFerguson** [comment]
I downloaded ruby-2.2.2.tar.gz from somewhere and compiled it myself.

Attached are the config.log and configure files

On Fri, Jun 26, 2015 at 8:33 AM, Sean Edge <notifications@github.com> wrote:

> @TobyHFerguson <https://github.com/TobyHFerguson> Did you compile ruby
> yourself or did you install a package from Oracle? If you compiled it
> yourself could you share your ./configure?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NARKOZ/gitlab/issues/135#issuecomment-115733221>.
>



-- 
toby

**Comment by asedge** [comment]
@TobyHFerguson What do you get when you do `ldd $(which ruby)` and `find /usr/local/lib -name readline.so`?

**Comment by TobyHFerguson** [comment]
```
[root@ca-ovsx32 ~]# ldd $(which ruby)
    linux-vdso.so.1 =>  (0x00007fffb18c1000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffbfcd4e000)
    librt.so.1 => /lib64/librt.so.1 (0x00007ffbfcb45000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00007ffbfc941000)
    libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007ffbfc70a000)
    libm.so.6 => /lib64/libm.so.6 (0x00007ffbfc485000)
    libc.so.6 => /lib64/libc.so.6 (0x00007ffbfc0f1000)
    /lib64/ld-linux-x86-64.so.2 (0x00000038a9800000)
    libfreebl3.so => /lib64/libfreebl3.so (0x00007ffbfbeee000)
[root@ca-ovsx32 ~]#

[root@ca-ovsx32 ~]# find / -mount -name readline.so
/opt/gitlab/embedded/lib/ruby/2.1.0/x86_64-linux/readline.so
/usr/lib64/python2.6/lib-dynload/readline.so
/usr/lib64/ruby/1.8/x86_64-linux/readline.so
[root@ca-ovsx32 ~]#
```

On Wed, Jul 8, 2015 at 8:46 AM, Sean Edge <notifications@github.com> wrote:

> @TobyHFerguson <https://github.com/TobyHFerguson> What do you get when
> you do ldd $(which ruby) and find /usr/local/lib -name readline.so?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NARKOZ/gitlab/issues/135#issuecomment-119630993>.
>



-- 
toby

**Comment by asedge** [comment]
@TobyHFerguson I only see `readline.so` for system Ruby (1.8) and Gitlab's embedded Ruby (2.1.0).  Not the 2.2.x Ruby you are trying to run.  I think the problem might be you were missing the `readline-devel` package when you built Ruby.  Try installing those header files and recompiling.

Disclaimer: I don't think it's a good idea to do any of this stuff on your Gitlab server - which appears to be what you're doing based on the `find` output.  A friend of mine put RVM on his Gitlab server and it caused so many problems that he ended up having to reinstall.

**Comment by TobyHFerguson** [comment]
Thanks for the information, sorry about the tardy response. 

Given my current constraints I'll have to forgo the pleasure of using this module then - the gitlab server is also the place where I'm attempting to run my programs, and with the warning above that's a problem! 

I'll close this issue for now. Thanks again for the support. Much appreciated.
