### ISSUE TITLE
 Failed to transfer project {:namespace=>["is invalid"]}

### ISSUE THREAD

**Issue by bulleric** [NARKOZ/gitlab#136]
If i  try to use transfer_project_to_group i got an api exception.

Gitlab::Error::BadRequest: Server responded with code 400, message: Failed to transfer project {:namespace=>["is invalid"]}.

**Comment by asedge** [comment]
It looks like that error is returned when the `allowed_transfer?` check [here](https://github.com/gitlabhq/gitlabhq/blob/ce5928f4df1ebdac1fbc319fd1dbd15585f5da9e/app/services/projects/transfer_service.rb#L18-L23) is false/failed.  The [docs](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/groups.md) say `Transfer a project to the Group namespace. Available only for admin`.  Do you have the proper access?

**Comment by bulleric** [comment]
Yea i created a bot user wich is admin. I also used the default administration account token.
Always the same problem.   Creation of new repos or groups are no problem but transferring  gives me this exception.

**Comment by lyio** [comment]
Have you tried transferring the project manually? Because last time I tried to do that, I couldn't do that via the web interface (the list of available namespaces was empty).
So it would be only natural, if the api threw an error there.

**Comment by bulleric** [comment]
yea  i tried. Worked without problems. 
In the list is every available namespace wich i checked with the gitlab console.

11 of 11  in my setup

**Comment by asedge** [comment]
@bulleric I would recommend adding your details to that GitlabHQ issue you referenced.

**Comment by bulleric** [comment]
There was a mistake in the api implementation. 
Sazor made a pull request to solve this issue.

ref: https://github.com/gitlabhq/gitlabhq/pull/9448
