### ISSUE TITLE
After deleting a project response body value contains "true", and could not be parsed as this case is not handled properly

### ISSUE THREAD

**Issue by aroq** [NARKOZ/gitlab#141]
![screen shot 2015-07-14 at 15 59 51](https://cloud.githubusercontent.com/assets/1021490/8676613/38a5bdfa-2a53-11e5-961d-1e214029c09a.png)

**Comment by asedge** [comment]
This is a duplicate of #138 and was fixed by #137.  Please try using the latest code on the master branch and reopen this if you still encounter problems.
