### ISSUE TITLE
How to configure the CLI client?

### ISSUE THREAD

**Issue by arne-cl** [NARKOZ/gitlab#143]
Dear Nihad,

your documentation lists a number of configuration options, but it doesn't mention where (i.e. in which file) I have to put them in order to use the CLI client.

Best regards,
Arne

**Comment by asedge** [comment]
@arne-cl The CLI just relies on some environment variables being set.  It doesn't read any specific file.  I just put a file in my home directory with a few export statements and source it when I want to use the CLI.

**Comment by raine** [comment]
Please document this in README.
