### ISSUE TITLE
Proxy settings not passed consistently

### ISSUE THREAD

**Issue by aepstein** [NARKOZ/gitlab#148]
I am using Gitlab in a Rails project and my development is behind a corporate proxy.  I put the following in the initializer to parse the proxy settings from an environment variable:

``` ruby
if ENV['HTTP_PROXY'] &&
    /(?<proxy_protocol>[a-z]+\:\/\/)(?<proxy_user>[^\:]+)\:(?<proxy_pass>[^\@]+)@(?<proxy_host>[^\:]+)\:(?<proxy_port>[0-9]+)/ =~ ENV['HTTP_PROXY']
    logger.info "Proxy detected: #{proxy_user}:#{proxy_pass[0..1]}@#{proxy_host}:#{proxy_port}"
    Gitlab.http_proxy( proxy_host, proxy_port.to_i, proxy_user, proxy_pass )
end
```

The log shows that the proxy information is correctly parsed, so I know it is calling the http_proxy method and passing the correct options to it.  The private token is stored in a user model, so I can retrieve the Gitlab instance like this:

``` ruby
class User
  include Mongoid::Document
  field :gitlab_private_token, type: String

  def gitlab
    return @gitlab if @gitlab
    return nil unless gitlab_private_token
    Gitlab.private_token = gitlab_private_token
    @gitlab = Gitlab
  end
end
```

So, for example, I should be able to retrieve projects for a user by calling:

``` ruby
u = User.first
u.gitlab.projects
=> SocketError
```

And here is the problem: This throws a "SocketError: getaddrinfo: Name or service not known" error.  However, it behaves as expected if I do the following:

``` ruby
u = User.first
u.gitlab.http_proxy host, port, user, pass
u.gitlab.projects
=> <Array of results>
```

**Comment by NARKOZ** [comment]
Can’t reproduce.

**Comment by asedge** [comment]
Sorry, this is a really old issue.  If you're still experiencing the problem please reopen and we can try to help you fix it.  Thanks!
