### ISSUE TITLE
Using OAuth tokens

### ISSUE THREAD

**Issue by augustf** [NARKOZ/gitlab#149]
When I first began trying to use this gem, I couldn't get it to authenticated with my Gitlab API. I soon realized that the user profile secret is totally different from the tokens offered for OAuth authentication. This is more down to the Gitlab API de-emphasizing user secrets in favor of OAuth panels for both users and admins (application-wide), but is there any plan to support OAuth tokens?

The Gitlab API apparently supports authentication with OAuth tokens now (http://doc.gitlab.com/ce/api/README.html), which would allow API access to be system-wide and not tied to a particular user, which is desirable in a lot of situations.

**Comment by asedge** [comment]
OAuth support was added in this PR: https://github.com/NARKOZ/gitlab/pull/109.  It should be available in 3.4.0, which is the latest official release.

**Comment by augustf** [comment]
@asedge I see that code all right. But whether I use config.private_token or config.auth_token to define the Gitlab OAuth key, it fails with a 403 response.

**Comment by asedge** [comment]
Sorry but I was never able to reproduce this.
