### ISSUE TITLE
How to create a new repp from CLI?

### ISSUE THREAD

**Issue by jitendravyas** [NARKOZ/gitlab#151]

**Comment by asedge** [comment]
In its simplest form: `gitlab create_project "<project_name>"`.  There are many options you can specify and [this page](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/projects.md) has them.  To specify options you would do: `gitlab create_project "MyProject" '{description: "This is my Project", public: true}'`.

**Comment by jitendravyas** [comment]
Thanks for reply. I tried `gitlab create_project "<project_name>"` and it worked. How to create a new repo from existing local repo where repo name could be project's folder name? so i can push my multiple local projects to my gitlab quickly

**Comment by asedge** [comment]
You would need to use the `remote` sub command of git.  I would recommend reading this: https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes.
