### ISSUE TITLE
cant create a project with cli

### ISSUE THREAD

**Issue by jave** [NARKOZ/gitlab#156]
I can list projects and do a lot of read operations, but not create a project.

I tried the example, and some variations.

  gitlab create_project 'viking' :description => 'Awesome project'

**Comment by asedge** [comment]
`gitlab create_project 'viking' "{description: 'Awesome project'}"`

**Comment by jave** [comment]
ok this works, thanks! 

But how do I create the project in a group? I tried group_id: 'test' where test was an existing group, the project was created but not in the group.

**Comment by asedge** [comment]
@jave, Look at the API documentation here: https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/projects.md.  You would need to specify the `namespace_id` as part of the options, which would be the group id number you want to create the project under.

**Comment by jave** [comment]
@asedge yes I figured that out, but suspected a namespace_id is not the same thing as a group_id.

I couldnt find a way to get namespace ids with the cli, so I got them with a curl call to the rest api, and then used the numerical namespace_id in my call.

curl http://gitlab.internal.se:50003/api/v3/namespaces?private_token=<token from user profile>
[{"id":38,"path":"shared","kind":"group"},...

 gitlab create_project 'viking10' "{description: 'Awesome project',  namespace_id: 38}"

I probably just as well could have done "gitlab groups" to get the id, im not sure if a group id is always a namespace id.

 gitlab create_project 'viking10' "{description: 'Awesome project',  group_id: 38}"

doesnt do the same thing in any case.

**Comment by jave** [comment]
anyway, i can create a project with the cli, and if anyone else is having problems they can read this, so i close the issue

**Comment by asedge** [comment]
@jave Namespace searching was just recently merged into the code here.  There hasn't been an official release yet though.  Anyway, a group ID is always a namespace ID.  The location for your (or any other users') personal projects is also a namespace so it would have its own ID.  Hopefully that clears up any confusion.
