### ISSUE TITLE
Support configuration from file

### ISSUE THREAD

**Issue by walterheck** [NARKOZ/gitlab#159]
I'm trying to set up this gem for it's cli functionality. I don't want to have to set up environment variables everytime I want to use it. 

It would be great if we could read some settings from /etc/gitlab/ or from ~/.gitlab/ or someplace else.

**Comment by asedge** [comment]
Couldn't you just set the environment variables in your shell's rc file?  E.g. $HOME/.bashrc.

**Comment by walterheck** [comment]
I'm not going to be running the gitlab cli only interactively, it will be called from different scripts possibly called by different users. All of them need to connect to the same endpoint though, so it would really make sense to load settings from a file imho?

**Comment by NARKOZ** [comment]
To do if for all users/shells, depending on distro you could use `/etc/environment` or `/etc/profile`. Creating a new file in `/etc/profile.d` may be preferable if it exists, as it will be less likely to conflict with updates made by the packaging system.

**Comment by walterheck** [comment]
/etc/profile is sourced at shell startup, that doesn't seem like the right place for application specific environment variables like this (changes in config won't be seen immediately).

**Comment by NARKOZ** [comment]
Support for the custom config files aren't planned. 

Use env variables or apply the patch from #107

**Comment by binford2k** [comment]
Refusing a config file makes it quite difficult to automate using the tool. There are ways to work around it, but they add silly levels of complexity to the tooling.

**Comment by walterheck** [comment]
Can I try to change your mind on accepting that #107? You have multiple people asking for it, the code is right there and it would make life much easier for some of us.
My specific usecase: I'm building a puppet type and provider to manage gitlab users (and later on all the other objects also) and that provider needs to get it's config for the gitlab api from somewhere. Doing that through environment variables is not an option.

**Comment by walterheck** [comment]
@NARKOZ any comments? Still struggling with this gem due to no config files :(

**Comment by NARKOZ** [comment]
Using environment variables should be enough for 99% of the cases.

**Comment by walterheck** [comment]
There are at least 2 people in this thread that fall into that 1%. Will it really hurt you as a maintainer to add a PR that has nice comments, tests and less then 100 lines of code to achieve something that would make life a lot easier? Isn't this the idea of open source software?

**Comment by NARKOZ** [comment]
@walterheck  I'm all for implementing a good feature that solves people's problems. By default the gitlab client uses environment variables which is a good practice. You can use `.bashrc`, `.profile`, `.zshrc`, etc. files to store and read configuration. The client also provides easy way to set/change configuration. Use it for your non-standard case.
I'm against of implementing redundant feature that will solve the same problem, but differently. Sorry.

**Comment by walterheck** [comment]
But it doesn't solve my problem at all, I would be very interested to have you show me how I'm supposed to make this work from Puppet with environment variables. I've been using puppet for a very long time and know it inside out. So has @binford2k. We're both telling you that this gem is nearly unusable from puppet as opposed to many other gems that do simply support configuration from file.

An example of how code looks now:
```puppet
 exec { 'gitlab-settings':
    command => "/bin/echo export GITLAB_API_PRIVATE_TOKEN=`/bin/curl -s -X POST -d 'password=${gitlab_api_password}&login=${gitlab_api_user}' ${gitlab_api_endpoint}/session | /bin/jq .private_token -r` > ~/.gitlab; /bin/echo export GITLAB_API_ENDPOINT=${gitlab_api_endpoint} >> ~/.gitlab",
    unless  => "/bin/test -f ~/.gitlab && /bin/grep '^export GITLAB_API_PRIVATE_TOKEN.*$' ~/.gitlab 1>/dev/null && /bin/grep '^export GITLAB_API_ENDPOINT.*$' ~/.gitlab 1>/dev/null",
    require => $exec_dependencies,
  } ->

  exec { "create-user-${title}":
    command => "/bin/bash -c 'source /root/.gitlab; /usr/local/bin/gitlab create_user \"${email}\" \"${password}\" \"${username}\" \"{name: \\\"${fullname}\\\"}\"'",
    unless  => "/bin/bash -c 'source /root/.gitlab; /usr/local/bin/gitlab users | /bin/grep $email'",
    path    => '/bin:/usr/local/bin',
    environment => 'HOME=/root',
    require => Package['gitlab-cli'],
  }
```

the same code would look much cleaner if we had a config file:
```puppet
  exec { "create-user-${title}":
    command => "/usr/local/bin/gitlab create_user \"${email}\" \"${password}\" \"${username}\" \"{name: \\\"${fullname}\\\"}\"",
    unless  => "/usr/local/bin/gitlab users | /bin/grep $email ",
    path    => '/bin:/usr/local/bin',
    environment => 'HOME=/root',
    require => Package['gitlab-cli'],
  }
```

the environment attribute  of the create-user exec can not be used here because it would mean we need to get those values from somewhere and querying them on every puppet run for every executed command from the gitlab instance is not viable.

**Comment by NARKOZ** [comment]
@walterheck

Use gitlab CLI instead of curl:

```
gitlab session USER PASS --json | jq .result.private_token -r
```

Then set `GITLAB_API_PRIVATE_TOKEN` env variable in puppet: http://stackoverflow.com/a/18417598
