### ISSUE TITLE
change create_project:public type

### ISSUE THREAD

**Issue by levyilan** [NARKOZ/gitlab#167]
gitlab server has 3 options for the project visibility level:
private
internal
public

currently create_project:public is Boolean and allows to set the project visibility level only to private or public.

**Comment by NARKOZ** [comment]
You can any options. The docs are outdated.

**Comment by levyilan** [comment]
may you please give an example how to create it, this is the command line I'm using:
gitlabcli create_project "cli_test" "{namespace_id: '17' , public: '10'}"

according to the API doc "10" should create a project with "internal: visibility level
http://doc.gitlab.com/ee/api/projects.html
Project visibility level

Project in GitLab has be either private, internal or public. You can determine it by visibility_level field in project.
Constants for project visibility levels are next:
    Private. visibility_level is 0. Project access must be granted explicitly for each user.
    Internal. visibility_level is 10. The project can be cloned by any logged in user.
    Public. visibility_level is 20. The project can be cloned without any authentication.

**Comment by asedge** [comment]
You should use the `visibility_level` key then pass 10 for `internal` visibility.
```gitlabcli create_project "cli_test" "{namespace_id: '17' , visibility_level: 10}"```

I just tried this and it worked fine on gitlab.com.
