### ISSUE TITLE
Mechanism to output array as comma-separated list? Or simplified output?

### ISSUE THREAD

**Issue by andy-nicholas** [NARKOZ/gitlab#168]
I'm new to the gitlab CLI tool. Is there a way to suppress the +-------+------- output so that the only output is a comma-separated list? This would be easier for downstream tools to parse as far as I can tell.

Or, is there a way to simplify the output from commands like "GitLab.users" so that only the name field is displayed? Or only display field #2 in a list, one field per line?

My goal is to be able to have a tool which dumps the list of users which are in a group on GitLab Server A and then add those same users to a differently named group on Server B.

**Comment by NARKOZ** [comment]
You can filter output by supplying `--only` or `--except` flags:

```
gitlab user --only=id,email,name
```

```
gitlab users --except=id,email,name
```

**Comment by andy-nicholas-ericsson** [comment]
Nice. My output looks like this below. How do I avoid the +------- ???

+----+------------------+
| Gitlab.users --only=id,name |
+----+------------------+
| id | name             |
+----+------------------+
| 77 | Jimmy Lo         |
+----+------------------+

**Comment by asedge** [comment]
Use `--json` for JSON output.

**Comment by andy-nicholas** [comment]
Oh yes, that's much better. I figured out how to avoid the paginated results also. Thanks.
