### ISSUE TITLE
--- !ruby/hash:ActionController::Parameters in title

### ISSUE THREAD

**Issue by ashender** [NARKOZ/gitlab#169]
gitlab create_merge_request 260 "title" "{source_branch: '13079', target_branch: 'v5.8.0', description: 'descr', target_project_id: 130, assignee_id: '97'}"

results in pullrequest with title that begins with:
--- !ruby/hash:ActionController::Parameters

**Comment by NARKOZ** [comment]
The problem is on the server side.

**Comment by ashender** [comment]
This actually happens when there is a colon in title. I've removed colon - and it works ok now.
