### ISSUE TITLE
Incorrect doc for `create_project`

### ISSUE THREAD

**Issue by dblessing** [NARKOZ/gitlab#174]
https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/projects.rb#L79

`group_id` is not a valid parameter for the endpoint per http://docs.gitlab.com/ee/api/projects.html#create-project. `namespace_id` is the parameter to allow you to create a project in a group.

If I get a chance I'll send a PR but I wanted to at least get it reported.

**Comment by NARKOZ** [comment]
Feel free to edit docs directly via Github. You have a collab access.

**Comment by dblessing** [comment]
Thanks for the reminder @NARKOZ. I never use the web editor so I forget about making quick edits that way.
