### ISSUE TITLE
Server responded with code 400, message: #<Gitlab::ObjectifiedHash:**>.

### ISSUE THREAD

**Issue by Vuuo** [NARKOZ/gitlab#185]
Hi, I have the following code in my script.
```ruby
  main_project = client.create_project(main_name, namespace_id: gid)
```

It created projects successfully a month ago when I ran it. However, I'm getting the following error msg today when I tried to run it again.

```
Server responded with code 400, message: #<Gitlab::ObjectifiedHash:0x00000001d26990>. Request URI: https://mygitlab.com/api/v3/projects (Gitlab::Error::BadRequest)
```

gitlab gem version: 3.2.0
gitlab version: 7.12.2

**Comment by NARKOZ** [comment]
Can you try with new version?

**Comment by Vuuo** [comment]
I actually found the reason. I printed out the `#<Gitlab::ObjectifiedHash:0x00000001d26990>` object. And the message attribute of the object says the project name has been taken.

Would be helpful if the message is displayed in the error msg.

**Comment by asedge** [comment]
I believe this has already been fixed in a newer version of the gem.  As @NARKOZ requested, can you try again with a newer version?  The latest release of this gem is 3.6.1.

**Comment by Vuuo** [comment]
:+1:

**Comment by aseslas** [comment]
@NARKOZ there a way to contact you privately? Really thank you very much
