### ISSUE TITLE
[Question] Projects under a group

### ISSUE THREAD

**Issue by iwubcode** [NARKOZ/gitlab#192]
I noticed that a feature was added that allowed a user to get  [projects under a specific group](https://github.com/NARKOZ/gitlab/commit/ac67e3da33054d12824262de7490683dccd99c5e), since I'm still on the released gem 3.6.1, I don't have access to that feature.

I faked it out by doing:  "get("/groups/#{id}/projects")".  However, that doesn't work for me, the gem gives me something similar to [Issue 179](https://github.com/NARKOZ/gitlab/issues/179) telling me to sign-in.  Doing the process manually in a browser ex:  <host>/api/v3/groups/[id]/projects gives me a 401 error.  The only thing I can think of is that the feature is not supported by my gitlab instance's version of the api?

However, when I do <host>/api/v3/groups/[id]  in a browser, I am able to get the group and I see there is indeed a json section for "projects".  So I thought maybe I could get the raw hash and get the projects section and just json parse it myself... but using "to_h" on the group object gives me the title and description of the group but the projects section doesn't exist.  Is there a way to get the raw json so that I can work around this issue?

(My apologies this was so long and I'm relatively new to github so I wasn't sure if a question should go here...)

**Comment by asedge** [comment]
>Doing the process manually in a browser ex: /api/v3/groups/[id]/projects gives me a 401 error. The only thing I can think of is that the feature is not supported by my gitlab instance's version of the api?

A 401 means the API had an issue authenticating you.  Double check your token?

**Comment by iwubcode** [comment]
> A 401 means the API had an issue authenticating you. Double check your token?

Thanks for the suggestion, I tried it again and I think I mistyped the first time (sorry), even with the private_token I get a **404** error.

**Comment by iwubcode** [comment]
I did some debugging by printing out what was coming back from httparty and found out a few things:

- Using group search does not return json data with the project information (I thought it did)
- Using get("/groups/id") actually gives the full json, using that I was able to parse the projects and get the data required

Thanks!
