### ISSUE TITLE
Exception in delete_merge_request_comment

### ISSUE THREAD

**Issue by iainsmith** [NARKOZ/gitlab#193]
I'm trying to delete another user's comment and get this exception.

`client.delete_merge_request_comment(project_id, pr_id, note_id)`

Stack Trace

```
NoMethodError: undefined method `message' for true:TrueClass

from /..2.2.0/gems/gitlab-3.6.1/lib/gitlab/request.rb:117:in `error_message'
from /../2.2.0/gems/gitlab-3.6.1/lib/gitlab/request.rb:72:in `validate'
from /../2.2.0/gems/gitlab-3.6.1/lib/gitlab/request.rb:61:in `delete'
from /../2.2.0/gems/gitlab-3.6.1/lib/gitlab/client/merge_requests.rb:125:in `delete_merge_request_comment'
```

**Comment by asedge** [comment]
Could you try this again with the latest release of the gem and report back if it's still an issue?  Thanks!

**Comment by asedge** [comment]
Reopen if you still have this issue with the latest version of the gem.
