### ISSUE TITLE
Feature requests: add tags support

### ISSUE THREAD

**Issue by jblackman** [NARKOZ/gitlab#199]
Please correct me if I am wrong, but is the tag part of the gitlab API not currently supported in this client?

https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/tag.md

If that's the case, I'd be happy to do the work to put them in.

**Comment by asedge** [comment]
We only have list and create:
https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/repositories.rb#L5-L34

Feel free to add missing methods.

Also check out [CONTRIBUTING.md](https://github.com/NARKOZ/gitlab/blob/master/CONTRIBUTING.md)
