### ISSUE TITLE
Get and set build variables from CLI

### ISSUE THREAD

**Issue by devth** [NARKOZ/gitlab#203]
Would be a useful addition, especially for copying build variables from one project to another.

**Comment by asedge** [comment]
This already exists: https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/build_variables.rb

I don't think I have the ability to release a new version of the gem without help from @NARKOZ though.

**Comment by devth** [comment]
:+1: I saw that; just didn't see a way to invoke via CLI.

**Comment by asedge** [comment]
What have you done to get the latest code?

**Comment by devth** [comment]
`gem install gitlab`

Invoking via: `gitlab` from my shell.

Yes, I tried `gitlab help`.

**Comment by devth** [comment]
@asedge makes sense. You could push to a new gem name if you wanted, like `gitlab2` or whatever.

**Comment by asedge** [comment]
I suppose I could, but I'm content to wait for @NARKOZ. Sorry!

**Comment by devth** [comment]
Was this ever released?
