### ISSUE TITLE
Where to store the configuration variables?

### ISSUE THREAD

**Issue by raarts** [NARKOZ/gitlab#205]
Hi,

I just installed gitlab, and read the doc. It mentions config settings like `Gitlab.endpoint`. I have been trying to find where to store those settings. Things I tried:

- reading the documentation
- `find $HOME -type f | xargs fgrep Gitlab.endpoint`
- clone the repo, and grep for open statements (I don't know Ruby)
- Google for it

Nothing worked. Please help.

**Comment by asedge** [comment]
`Gitlab.endpoint=` would be used if writing Ruby.

Can you explain what you're trying to accomplish?

**Comment by asedge** [comment]
If you're looking to set the configuration variables for the CLI you should have a look again at the [README.md](https://github.com/NARKOZ/gitlab/blob/master/README.md).  There are environment variables that can be set.

**Comment by raarts** [comment]
Yes, that was indeed what I was trying to do. I've seen that section, but I took it as just being a workaround if you don't set the config file. Thanks.
