### ISSUE TITLE
What about a new release?

### ISSUE THREAD

**Issue by rolfschmidt** [NARKOZ/gitlab#206]
Hi,
im very interested in the builds functions. Could you please create a new release?

Relates: https://github.com/NARKOZ/gitlab/pull/194

Best regards,
Rolf

**Comment by k0nserv** [comment]
Bump :)

**Comment by k0nserv** [comment]
@asedge News on this? I wanna use this gem in danger/danger for gitlab support

**Comment by asedge** [comment]
I think only @NARKOZ can release a new version of this gem.  He hasn't been around in a while though so no ETA right now, sorry!

**Comment by orta** [comment]
@asedge - it's possible that as a core contributor to this repo, you can request to be added by the rubygems admins ( I manage this in [cocoapods](https://cocoapods.org), where we get this requests every few days )

**Comment by asedge** [comment]
@orta OK, thanks.  Someone from Gitlab reached out to me last week to discuss how to proceed.  Waiting to hear back from them.  I'll see what the admins at rubygems have to say as well.

**Comment by k0nserv** [comment]
@asedge any word? I haven't heard anything from the admins at rubygems personally

**Comment by jvanbaarsen** [comment]
@asedge Let me see what I can do! Who did you talk to?

**Comment by jvanbaarsen** [comment]
@asedge I've opened a ticket with the Rubygems people. I'll update here when I hear back

**Comment by asedge** [comment]
@k0nserv Nothing so far.

@jvanbaarsen I have as well.

**Comment by jvanbaarsen** [comment]
@asedge :+1:

**Comment by rolfschmidt** [comment]
@asedge :+1:

**Comment by jvanbaarsen** [comment]
@asedge I just got owner permissions on the gem. What is your rubygems username? So I can add you as well?

**Comment by asedge** [comment]
@jvanbaarsen It's `asedge`, pretty original right? Also, how did you get them to respond so fast?

**Comment by jvanbaarsen** [comment]
@asedge I don't know? Maybe it helped that I'm also a Gitlab Core member? Anyway, will add you!

**Comment by jvanbaarsen** [comment]
@asedge I need your email address in order to add you.

**Comment by asedge** [comment]
Its my username at gmail, same email I use for Github.

**Comment by jvanbaarsen** [comment]
:+1:

**Comment by jvanbaarsen** [comment]
@asedge I made you gem owner. Is it correct that you don't own any other gems on Rubygems?

**Comment by asedge** [comment]
Yes, I created the account to file the ticket.

**Comment by asedge** [comment]
@jvanbaarsen Looks good, I'm able to see it in my profile now... Thanks!

**Comment by jvanbaarsen** [comment]
:+1:

**Comment by asedge** [comment]
3.7.0 released! https://github.com/NARKOZ/gitlab/commit/6dcd3eabd2b849b43e29364263668b6ff0a8a269
