### ISSUE TITLE
New commits api params support

### ISSUE THREAD

**Issue by thierryxing** [NARKOZ/gitlab#212]
Hi, NARKOZ

There are two new params 'since' and 'until' in commits api, so could you make a new release to support this feature?

[http://docs.gitlab.com/ce/api/commits.html](http://docs.gitlab.com/ce/api/commits.html)

`GET /projects/:id/repository/commits`

> 
since	string	no	Only commits after or in this date will be returned in ISO 8601 format YYYY-MM-DDTHH:MM:SSZ
until	string	no	Only commits before or in this date will be returned in ISO 8601 format YYYY-MM-DDTHH:MM:SSZ

Thank you very much

**Comment by asedge** [comment]
We allow arbitrary options to be passed to the `commits` method so this should already be possible with the current release.

**Comment by asedge** [comment]
Please re-open if you're unable to use the new params.

**Comment by thierryxing** [comment]
Got it! Thank you
