### ISSUE TITLE
Consider adding "netrc" support?

### ISSUE THREAD

**Issue by al-the-x** [NARKOZ/gitlab#213]
Instead of (or in addition to) using environment variables to store authentication credentials for the CLI, consider reading credentials from `.netrc` with gem `netrc` as implemented in several other gems. Storing sensitive auth creds in the user's env leads some to append to `.profile` and then attempt to store that in a public `dotfiles` repo.

**Comment by asedge** [comment]
The original creator of this gem never seemed to like the idea of adding different ways to store credentials so unfortunately I say no.
