### ISSUE TITLE
Share project with group

### ISSUE THREAD

**Issue by danhalligan** [NARKOZ/gitlab#214]
The [gitlab API](http://docs.gitlab.com/ce/api/projects.html) lists an option to "[Share project with group](http://docs.gitlab.com/ce/api/projects.html#share-project-with-group)" which I cannot find in the ruby API. I am happy to admit I may have missed this, but if this is not currently implented I would like to make a request for this feature.

**Comment by asedge** [comment]
I don't believe this exists.  Contribution is welcome, please see [CONTRIBUTING.md](https://github.com/NARKOZ/gitlab/blob/master/CONTRIBUTING.md) if interested.
