### ISSUE TITLE
Award Emoji API endpoints

### ISSUE THREAD

**Issue by connorshea** [NARKOZ/gitlab#218]
See the [Award Emoji](http://docs.gitlab.com/ce/api/award_emoji.html) documentation.

For Issues and Merge Requests:
- `get_award_emoji`: Gets the award emoji awarded to an Issue or Merge Request.
  - `GET /projects/:id/issues/:issue_id/award_emoji`
  - `GET /projects/:id/merge_requests/:merge_request_id/award_emoji`
- `add_award_emoji`: Awards an emoji to an Issue or Merge Request.
  - `POST /projects/:id/issues/:issue_id/award_emoji`
  - `POST /projects/:id/merge_requests/:merge_request_id/award_emoji`
- `remove_award_emoji`: Removes an award emoji from an Issue or Merge Request.
  - `DELETE /projects/:id/issues/:issue_id/award_emoji/:award_id`
  - `DELETE /projects/:id/merge_requests/:merge_request_id/award_emoji/:award_id`

For notes (comments) the endpoints require passing the issue/MR ID and the note ID, then passing the award emoji ID to that. See the [Award Emoji on Notes](http://docs.gitlab.com/ce/api/award_emoji.html#award-emoji-on-notes) section.

**Comment by akkee** [comment]
#297 should have closed it.

**Comment by connorshea** [comment]
Thanks! :D
