### ISSUE TITLE
Todos API Endpoints

### ISSUE THREAD

**Issue by connorshea** [NARKOZ/gitlab#219]
See [the documentation for Todos](http://docs.gitlab.com/ce/api/todos.html).

We'd need:
- `get_todos`: `GET /todos`
- `mark_todo_as_done`: `DELETE /todos/:id`
- `mark_all_todos_as_done`: `DELETE /todos`

It'd also be nice to have `add_todo` and `mark_todo_as_done` methods for issues/MRs, see http://docs.gitlab.com/ce/api/merge_requests.html#create-a-todo and http://docs.gitlab.com/ce/api/issues.html#create-a-todo for creating Todos for an Issue/MR.

Marking an Issue/MR as done isn't as easy since there isn't an endpoint for that, it's expected that you use the `DELETE /todos/:id` endpoint (maybe that should be added to the API in GitLab itself?).

**Comment by akkee** [comment]
#290 Should have closed it.

**Comment by asedge** [comment]
@akkee - For future reference: https://github.com/blog/1506-closing-issues-via-pull-requests
