### ISSUE TITLE
Subscribe to/Unsubscribe from a label

### ISSUE THREAD

**Issue by connorshea** [NARKOZ/gitlab#220]
Add `subscribe_to_label` and `unsubscribe_from_label` methods to `lib/client/labels.rb`.
- `subscribe_to_label`
  - http://docs.gitlab.com/ce/api/labels.html#subscribe-to-a-label
  - `POST /projects/:id/labels/:label_id/subscription`
- `unsubscribe_from_label`
  - http://docs.gitlab.com/ce/api/labels.html#unsubscribe-from-a-label
  - `DELETE /projects/:id/labels/:label_id/subscription`

**Comment by akkee** [comment]
#296 should have closed it.

**Comment by connorshea** [comment]
Awesome, thanks :)
