### ISSUE TITLE
Subscribe to/Unsubscribe from an Issue or Merge Request

### ISSUE THREAD

**Issue by connorshea** [NARKOZ/gitlab#221]
Add `subscribe_to_*` and `unsubscribe_from_*` methods to `lib/client/issues.rb` and `lib/client/merge_requests.rb`.
- `subscribe_to_issue`/`subscribe_to_merge_request`:
  - http://docs.gitlab.com/ce/api/issues.html#subscribe-to-an-issue
  - http://docs.gitlab.com/ce/api/merge_requests.html#subscribe-to-a-merge-request
  - `POST /projects/:id/issues/:issue_id/subscription`
  - `POST projects/:id/merge_requests/:merge_request_id/subscription`
- `unsubscribe_from_issue`/`unsubscribe_from_merge_request`:
  - http://docs.gitlab.com/ce/api/issues.html#unsubscribe-from-an-issue
  - http://docs.gitlab.com/ce/api/merge_requests.html#unsubscribe-from-a-merge-request
  - `DELETE /projects/:id/issues/:issue_id/subscription`
  - `DELETE /projects/:id/merge_requests/:merge_request_id/subscription`

**Comment by newellista** [comment]
Unsubscribe should be implemented as `POST`s to the `unsubscribe` endpoint, per the latest documentation.
