### ISSUE TITLE
projects/:id/keys is deprecated, should use deploy_keys endpoint

### ISSUE THREAD

**Issue by connorshea** [NARKOZ/gitlab#222]
8.10 deprecated the `projects/:id/keys/...` API endpoint in favor of `projects/:id/deploy_keys/...`.

To ensure nothing is broken with the next major release, these endpoints should be updated in `projects.rb` :)

See: https://github.com/NARKOZ/gitlab/blob/6dcd3eabd2b849b43e29364263668b6ff0a8a269/lib/gitlab/client/projects.rb#L328-L377

Not sure if there's a policy on this? Should it use the new format only (won't fork for versions below 8.10) or is there a way for the user to communicate their specific GitLab version to the gem?

**Comment by asedge** [comment]
I'm really not sure what to do if Gitlab introduces backwards incompatible changes in a non-major release.  Considering I do this as a volunteer, the best I can hope to do is support the latest, released code in Gitlab.

**Comment by asedge** [comment]
Perhaps I misunderstood what you meant.  `projects/:id/keys/...` still works for me in 8.16.

**Comment by connorshea** [comment]
@asedge our current plan is to release 9.0 with API v3 and v4 supported, and then remove v3 a few releases down the road.
