### ISSUE TITLE
Enable/Disable deploy keys

### ISSUE THREAD

**Issue by connorshea** [NARKOZ/gitlab#223]
Add `enable_deploy_key` and `disable_deploy_key` methods to `projects.rb`.
- `enable_deploy_key`
  - http://docs.gitlab.com/ce/api/deploy_keys.html#enable-a-deploy-key
  - `POST /projects/:id/deploy_keys/:key_id/enable`
- `disable_deploy_key`
  - http://docs.gitlab.com/ce/api/deploy_keys.html#disable-a-deploy-key
  - `DELETE /projects/:id/deploy_keys/:key_id/disable`

**Comment by newellista** [comment]
This seems to have been resolved by https://github.com/NARKOZ/gitlab/pull/247
