### ISSUE TITLE
Update the documentation for labels.rb with description option

### ISSUE THREAD

**Issue by connorshea** [NARKOZ/gitlab#224]
Update documentation to mention the ability to add/modify a label's description from the API:
http://docs.gitlab.com/ce/api/labels.html#edit-an-existing-label

Currently it [only mentions name and color as options](https://github.com/NARKOZ/gitlab/blob/6dcd3eabd2b849b43e29364263668b6ff0a8a269/lib/gitlab/client/labels.rb#L16-L43).

**Comment by abrophy** [comment]
@asedge @NARKOZ checked the label api client class and this issue seems to have been resolved. should be good to close
