### ISSUE TITLE
Add @see comments to all methods

### ISSUE THREAD

**Issue by connorshea** [NARKOZ/gitlab#225]
In case the gem falls behind the API (for example #224), each method should link to the relevant section in the GitLab API Docs.

For example, for this:

``` ruby
# Creates a new label.
#
# @example
#   Gitlab.create_label(42, "Backlog", '#DD10AA')
#
# @param  [Integer] project The ID of a project.
# @option [String] name The name of a label.
# @option [String] color The color of a label.
# @return [Gitlab::ObjectifiedHash] Information about created label.
def create_label(project, name, color)
  post("/projects/#{project}/labels", body: { name: name, color: color })
end
```

We would add the following line after the return statement:

``` ruby
# @see http://docs.gitlab.com/ce/api/labels.html#create-a-new-label
```

This'd be kind of menial work, but it'd be pretty useful for end-users of the gem.

**Comment by connorshea** [comment]
Another example of this are the `create_issue` and `edit_issue` methods, which [lack some recently-added options](https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/issues.rb#L65-L70), e.g. `confidential` and `due_date` from the [actual API](http://docs.gitlab.com/ce/api/issues.html#edit-issue).

**Comment by connorshea** [comment]
I've sort of started working on this with #232.

**Comment by asedge** [comment]
#232 Was merged into master.  I guess we don't need this issue anymore.  If I'm wrong, feel free to reopen.
