### ISSUE TITLE
A little bug.

### ISSUE THREAD

**Issue by xr081221097** [NARKOZ/gitlab#244]
Hi, nice authors.
I found a little bug.
In file:lib/gitlab/error.rb, line 32 and 33:
`parsed_response = @response.parsed_response`
`message = parsed_response.message || parsed_response.error`
[Original code](https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/error.rb#L32)
When the @response has content type "application/json", @response.parsed_response will return a hash. So, parsed_response has no method "message" or "error", but has method with parameter '["message"]' or '["error"]'
Thank you.

**Comment by xr081221097** [comment]
@asedge , @NARKOZ , could you please help to fix this? Thank you.

**Comment by jvanbaarsen** [comment]
@xr081221097 Both of the users you mentioned are doing this in their spare time. If this is really blocking you, you can always try to solve it yourselve.

Please don't urge/push authors to fix your problems.

**Comment by asedge** [comment]
@xr081221097 I would welcome a pull request that fixes this.  Have a look at the [CONTRIBUTING.md](https://github.com/NARKOZ/gitlab/blob/master/CONTRIBUTING.md).

**Comment by xr081221097** [comment]
OK, Thank you. I'll try my best to fix it. I have fixed it locally. The main reason that I won't fix myself is that my code of implementation maybe in low quality.  Please give any suggestions if you like.

**Comment by asedge** [comment]
> The main reason that I won't fix for the repo is that my code of implementation maybe in low quality.

That's why we review the changes before merging in the code and make suggestions as necessary. My suggestion right now is to look over the contributing guide, make a good PR (with tests), and we'll go from there.  You might learn a better way to write the code, I'll get better at reviewing code, and the gem will get better as a result of having a bug fixed.  Win, win, win... right?

**Comment by epintozzi** [comment]
@xr081221097, are you sure this is an issue?  I'm working with the API and am seeing the responses (of content-type `application/json`) get parsed correctly into an `ObjectifiedHash`.  I was looking into this, but am unable to reproduce it.  Do you possibly have more information on the specific endpoint you are trying to hit?

```
[1] pry(#<Gitlab::Error::NotFound>)> @response
=> #<Gitlab::ObjectifiedHash:70285915413240 {hash: {"message"=>"404 Project Not Found"}}
[2] pry(#<Gitlab::Error::NotFound>)> @response.parsed_response
=> #<Gitlab::ObjectifiedHash:70285915413240 {hash: {"message"=>"404 Project Not Found"}}
[3] pry(#<Gitlab::Error::NotFound>)> @response.parsed_response.message
=> "404 Project Not Found"
[4] pry(#<Gitlab::Error::NotFound>)> @response
=> #<Gitlab::ObjectifiedHash:70285915413240 {hash: {"message"=>"404 Project Not Found"}}
[5] pry(#<Gitlab::Error::NotFound>)> @response.headers
=> {"server"=>["nginx"], "date"=>["Thu, 02 Mar 2017 02:34:22 GMT"], "content-type"=>["application/json"], "content-length"=>["35"], "connection"=>["close"], "cache-control"=>["no-cache"], "vary"=>["Origin"], "x-request-id"=>["4e0d7bc4-7062-4605-b25b-aca13826eb7f"], "x-runtime"=>["0.069437"]}
[6] pry(#<Gitlab::Error::NotFound>)> @response.headers['content-type']
=> "application/json"
```

**Comment by asedge** [comment]
Feel free to reopen if this is still a problem or you have more data that can help duplicate the issue.
