### ISSUE TITLE
Support Pipelines

### ISSUE THREAD

**Issue by LouisKottmann** [NARKOZ/gitlab#248]
Hello,

Currently the Pipeline API, as defined [here](https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines) is not supported.

Is there any plan to support it?

Regards

**Comment by asedge** [comment]
At this point I only really have time to review PRs.  If you'd like to add the feature your contribution would be welcome.  [CONTRIBUTING.md](https://github.com/NARKOZ/gitlab/blob/master/CONTRIBUTING.md) - for reference on how to contribute.
