### ISSUE TITLE
Can't seem to enable any service

### ISSUE THREAD

**Issue by arioch** [NARKOZ/gitlab#250]
Please consider the snippet below.
It's identical to the example in [services.rb](https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/services.rb) and [services_spec.rb](https://github.com/NARKOZ/gitlab/blob/master/spec/gitlab/client/services_spec.rb).

```
Gitlab.change_service(42, :redmine, { new_issue_url: 'https://example.com/projects/test_project/issues/new',
                                      project_url: 'https://example.com/projects/test_project/issues',
                                      issues_url: 'https://example.com/issues/:id' })
```

When I run this my service is not enabled nor is it configured.

```
{"id"=>1684,
 "title"=>"Redmine",
 "created_at"=>"2016-09-06T12:11:48.198Z",
 "updated_at"=>"2016-09-06T12:11:48.198Z",
 "active"=>false,
 "push_events"=>true,
 "issues_events"=>true,
 "merge_requests_events"=>true,
 "tag_push_events"=>true,
 "note_events"=>true,
 "build_events"=>true,
 "pipeline_events"=>false,
 "properties"=>{}}
```

I would expect ```properties```to be filled out and ```active``` to be flipped.

I'm obviously missing something here.
Could somebody please point me in the right direction?

Update: using the gitlab gem version 3.7.

**Comment by asedge** [comment]
@arioch I just tried this out and it worked fine for me.  I used the example you posted just with a different project id.  When I ran it all I got back was `true`

Are you in a position to check the logs on your Gitlab instance?

**Comment by arioch** [comment]
I can't reproduce this anymore in a more recent version of Gitlab.
Must've been a bug that's been fixed in the meantime.

I'll go ahead and close this ticket.
