### ISSUE TITLE
get project with namespace

### ISSUE THREAD

**Issue by logicminds** [NARKOZ/gitlab#258]
How do I get a project with a name only and not the id including the namespace.

client.project('namespace/project') does not seem to work and shows 404

**Comment by asedge** [comment]
The code to make this work without needing to url encode the `namespace/project` was recently merged (#253) and is not yet released to RubyGems as I'm hoping for some kind of resolution for #241 before releasing.  I would say building the gem locally (with a version < 4.0.0) is your best option until the next release.
