### ISSUE TITLE
get runner with id must be a string

### ISSUE THREAD

**Issue by logicminds** [NARKOZ/gitlab#259]
Despite the return value of `client.runners.first.id` being a number the gitlab gem does not seem to allow getting a single runner by number only a string.

So the following does not work:

`client.runners(33232)`

however this does work `client.runners('33232')`

**Comment by asedge** [comment]
You should be using the `runner` method: https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/runners.rb#L34-L44.  That behavior is undocumented by GitlabHQ.
