### ISSUE TITLE
Support for attachment upload

### ISSUE THREAD

**Issue by lloeki** [NARKOZ/gitlab#266]
From the doc: https://gitlab.adhoc-gti.com/help/api/projects.md#uploads

How python does it: https://github.com/gpocentek/python-gitlab/pull/239/files

This is effectively a `requests` call for MultiPart: http://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file

**Comment by danyill** [comment]
:+1:

**Comment by mroutis** [comment]
I'll take it @NARKOZ !
