### ISSUE TITLE
Force update / sync with repositories

### ISSUE THREAD

**Issue by dannycochran** [NARKOZ/gitlab#267]
This may be a constraint of the lower level Gitlab API, but is it possible to force an update / sync with repositories? Otherwise this has to be done manually in the UI in order to see merge request details.

This question was also posed on the Gitlab forum, unanswered:
https://forum.gitlab.com/t/force-mirror-update-through-api/6495

**Comment by asedge** [comment]
It does not appear to be possible.  Though you could adjust the mirror sync timing: https://docs.gitlab.com/ee/workflow/repository_mirroring.html#adjusting-synchronization-times

**Comment by dannycochran** [comment]
Thanks, I decided I should probably not be mirroring the host repository, but pushing changes to it instead.
