### ISSUE TITLE
cut a new release

### ISSUE THREAD

**Issue by logicminds** [NARKOZ/gitlab#270]
httparty has a new version that updates json support.  I am getting some gem conflicts as a result.  

The 3.7.0 release of gitlab gem uses the older httparty 13.x gem that causes these conflicts.

I don't know if using 3.8 release would break semver guidelines since the gemspec dependencies changed, but it would be good to have a new release before the 4.x release with new gitlab 9.0 API changes.

**Comment by asedge** [comment]
A new release is coming soon.  It will be version `4.0.0` so we can drop older Ruby support.  It will also drop support for APIv3.

**Comment by asedge** [comment]
Released `4.0.0`
