### ISSUE TITLE
accept_merge_request fails to set custom commit message

### ISSUE THREAD

**Issue by hjanuschka** [NARKOZ/gitlab#277]
accepting merge requests with custom commit message: `merge_commit_message` does not work.

eg.:

```ruby
g.accept_merge_request(project.id, mr.iid,  { merge_commit_message: ':robot_face:  merging beta into master [ci skip]' })
```

whereas by plain network api it works:
```ruby
fastlane_require 'faraday'
  conn = Faraday.new(:url => "http://gitlab.xxxx.at/api/v4/projects/226/merge_requests/12/merge") do |faraday|
    faraday.request  :url_encoded             # form-encode POST params
    faraday.response :logger                  # log requests to STDOUT
    faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
  end
  conn.put do |req|
    req.headers['PRIVATE-TOKEN'] = 'xxxxx'
    req.body = {merge_commit_message: "Some custom message"}
  end

```

i suspect the content cannot be json?
any ideas?

**Comment by asedge** [comment]
Did you get an error? If so, can you share it?

**Comment by kennixdev** [comment]
sometime, it missing Content-Type:application/x-www-form-urlencoded in header

**Comment by hjanuschka** [comment]
@asedge i don't get any error - MR is accepted but not with custom commit message.
i bet its because of the content-type. (as it works using faraday)

**Comment by asedge** [comment]
@hjanuschka @kennixdev #268 adds the `Content-Type` header.  Can either of you apply that fix and try it out, please?

**Comment by hjanuschka** [comment]
@asedge i tested it with #268 and it works commit message is set correctly.

**Comment by asedge** [comment]
OK, great!  I merged it and will cut a release soon.
