### ISSUE TITLE
Gitlab.repo_file_contents returns 404 if ref parameter contains a dash

### ISSUE THREAD

**Issue by easy-petr** [NARKOZ/gitlab#284]
Hi

due to issue #113 I cannot get file content from branch that have a dash in name.

I had to create my own method as quick fix:

class Gitlab::Client
  module RepositoryFiles

    def file_contents_no_encode(project, filepath, ref='master')
      # ref = URI.encode(ref, /\W/) - cannot be here or rewrite it
      get "/projects/#{url_encode project}/repository/files/#{url_encode filepath}/raw",
          query: {ref: ref},
          format: nil,
          headers: {Accept: 'text/plain'},
          parser: ::Gitlab::Request::Parser
    end

  end
end

**Comment by sspans** [comment]
We're running into the same issue, with a file named 'ua.cfg', this needs to be encoded to work.

Broken:
```
[18/Jul/2017:13:44:06 +0200] "GET /api/v3/projects/Security-usermatrix/repository/files/ua.cfg/raw?ref=master HTTP/1.1" 404 32 "-" 47024
```

With proper encoding:
```
[18/Jul/2017:13:44:21 +0200] "GET /api/v3/projects/Security%2Fusermatrix/repository/files/ua%2Ecfg/raw?ref=master HTTP/1.1" 200 144878 "-" 61982
```

The suggested fix:
```
class Gitlab::Client
  module RepositoryFiles
    def file_contents(project, filepath, ref='master')
      ref = URI.encode(ref, /\W/)
      get "/projects/#{URI.encode(project, /\W/)}/repository/files/#{URI.encode(filepath, /\W/)}/raw",
          query: { ref: ref},
          format: nil,
          headers: { Accept: 'text/plain' },
          parser: ::Gitlab::Request::Parser
    end
  end
end
```

**Comment by asedge** [comment]
@easy-petr It looks like you're right.  Maybe at some point that `URI.encode` helped but it seems now to only cause problems.  I'll push a fix soon.

**Comment by asedge** [comment]
@sspans This isn't the same issue.  Can you please open a new one?  OP's issue relates to encoding `ref`, yours has to do with `filepath`.  Once you've created a new issue I'll push up a fix for that as well.  Thanks!

**Comment by easy-petr** [comment]
@asedge  Thank you for a fix
