### ISSUE TITLE
`delete_branch` & `repo_delete_branch` with project names return 404s

### ISSUE THREAD

**Issue by jaepd** [NARKOZ/gitlab#300]
According to the documentation:
```
= Gitlab::Client::Branches.delete_branch

(from gem gitlab-4.1.0)
=== Implementation from Branches
------------------------------------------------------------------------------
  delete_branch project branch

------------------------------------------------------------------------------

Deletes a repository branch.  Requires Gitlab >= 6.8.x

@example
  gitlab delete_branch 3 'api'
  gitlab repo_delete_branch 5 'master'

@param  [Integer String] project The ID or name of a project.
@param  [String] branch The name of the branch to delete
@return [Gitlab::ObjectifiedHash]

``` 
we should be able to supply the project name string to identity the project. However, it doesn't work:
```
message: 404 Not Found. Request URI: https://<gitlab server>/api/v4/projects/<project>/repository/branches/<branch name>
```
is apparently invalid and . A couple notes:
- The relevant branch is correctly found by this tool
- The relevant branch can be deleted (I can delete it through the Gitlab website)
- I have read/write permissions successfully set up in this tool (I can manage MRs/etc fine)
- Neither a `<project>` string of `<group>/<repo>` or `<repo>` work

I had to use the project ID to delete branches.

Thanks!

**Comment by asedge** [comment]
I can understand why you redacted your Gitlab server hostname but not the project or the branch.

I looked briefly at the Gitlab API for `Branches` and despite what the docs say it looks like you cannot use `group/repo`: https://github.com/gitlabhq/gitlabhq/blob/master/lib/api/branches.rb#L12.  However when it tries to lookup the project it looks by the full path: https://github.com/gitlabhq/gitlabhq/blob/master/lib/api/helpers.rb#L48.  You may want to raise an issue with Gitlab itself.

**Comment by jaepd** [comment]
Thanks! I'll check that out.
