### ISSUE TITLE
Unexpected behavior on `Gitlab.create_project`

### ISSUE THREAD

**Issue by j0an** [NARKOZ/gitlab#303]
Hi guys

Today I started having problem with the `create_project` method. 

I'm using the latest version of this gem, and also we are running an updated version of Gitlab CE (9.3.6)

The behavior is that when I'm trying to create a project, I execute `Gitlab.create_project('name', { namespace_id: 4 })` (either in my code and in the rails console) and not only do not create the project, also shows a response like a `Gitlab.projects` response (an Gitlab::ObjectifiedHash with the latest 10 created projects).

I tested my Gitlab installation doing some `curl` and everything goes fine.
I also tested in an old version of my company software (that currently runs 3.7.0 of this gem) and I'm getting the same issue.
I also tested pointing to /v3 and /v4 version of API.

Any thought about this issue?

**Comment by asedge** [comment]
Did you really execute `Gitlab.create_project('name', namespace_id :4)` or is that a typo?

**Comment by j0an** [comment]
@asedge `Gitlab.create_project('name', { namespace_id: 4 })` it was a typo.

**Comment by j0an** [comment]
Nevermind, I found that we can a problem with the SSL of the server so the `POST` verb where converted to a `GET` with a 301 redirect.

Not a problem with this gem.

Thanks for the magic, anyway ✨
