### ISSUE TITLE
snippets require visibility option

### ISSUE THREAD

**Issue by logicminds** [NARKOZ/gitlab#310]
https://docs.gitlab.com/ee/api/snippets.html

The current docs in this gem for the snippets api do not show visibility as being required.

**Comment by logicminds** [comment]
https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/snippets.rb#L31

**Comment by NARKOZ** [comment]
Pull request is welcome

**Comment by timofonic** [comment]
@NARKOZ Great, but would you consider interesting to provide some guidelines to possible contributor(s) about this? :)

**Comment by Rubemlrm** [comment]
i thinks this issue can be closed already. what do you think ?
