### ISSUE TITLE
Add Access Requests API

### ISSUE THREAD

**Issue by Tuckie** [NARKOZ/gitlab#315]
For my use it would be primarily viewing and approving of group and project access requests.

https://gitlab.com/help/api/access_requests.md

**Comment by abrophy** [comment]
I'd like to try my hand at this one as well

**Comment by sotayamashita** [comment]
@abrophy Are you still working?

**Comment by abrophy** [comment]
if you'd rather take a crack at it be my guest, sorry for leaving this thread dangling
