### ISSUE TITLE
Search issues?

### ISSUE THREAD

**Issue by claytonrcarter** [NARKOZ/gitlab#316]
Forgive me if I'm missing something, but is it possible to search for issues via CLI?

If not, would something like this get it to work? (Sorry, I'm not very good with ruby.)

```ruby
# somewhere in lib/gitlab/client/issues.rb
def search_issues(project, search, options={})
      get("/projects/#{url_encode project}/issues?search=#{url_encode search}", query: options)
end
```

GitLab API docs for issue search: https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/issues.md#list-project-issues

**Comment by asedge** [comment]
It appears as though this is is already possible.  Try something like this:
```bash
# Search all issues. You could specify the project as 0 rather than the empty string - either should work. 
$ gitlab issues '' '{search: "search string"}'
# Search issues in a project
$ gitlab issues 'my-group/my-project' '{search: "search string"}'
```

**Comment by claytonrcarter** [comment]
Ah, of course. Works perfectly. Thank you!
