### ISSUE TITLE
Feature request: Add support to add a label in a MR

### ISSUE THREAD

**Issue by fabioperrella** [NARKOZ/gitlab#323]
Hi!

It would be nice if it was possible to set (or add) a label when creating a MR, or even after creating one.

Based in the class https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/merge_requests.rb I think this is not possible yet, isn't it?

**Comment by fabioperrella** [comment]
forget it, I found how to set a label!

```
{source_branch: 'depends-on-recipe-2', target_branch: 'depends-on-recipe', labels: 'novo_provisionamento'}
```

**Comment by fabioperrella** [comment]
Could you add the label `hacktoberfest` to this MR pls? So my MR will participate in https://hacktoberfest.digitalocean.com

**Comment by NARKOZ** [comment]
@fabioperrella add in PR
