### ISSUE TITLE
Allow putting configuration in .git/config

### ISSUE THREAD

**Issue by strk** [NARKOZ/gitlab#328]
It is useful to record API endpoints in each git repository configuration, for when you have multiple repositories deal with multiple gitlab hosting services...

**Comment by strk** [comment]
This is how I ended up doing it, in a `/usr/local/bin/git-lab` script, so you can use with `git lab`:
```
#!/bin/sh

endpoint=`git config gitlab.api.endpoint`
if test -z "${endpoint}"; then
  echo "No endpoint defined, please use:" >&2
  echo "  git config gitlab.api.endpoint \${endpoint}" >&2
  echo "Endpoint is like: https://gitlab.yourcompany.com/api/v4" >&2
  exit 1
fi

baseurl=`echo ${endpoint} | sed 's|/api/v4$||'`

token=
if test -f ~/.gitlab-tokens; then
  token=`grep "^${baseurl} " ~/.gitlab-tokens | cut -d' ' -f2`
fi

if test -z "${token}"; then
  echo "No private token found for endpoint ${baseurl} in ~/.gitlab-tokens, try adding it:" >&2
  echo "  echo ${baseurl} \${token} >> ~/.gitlab-tokens" >&2
  echo "You can find your private token on ${baseurl}/profile/account" >&2
  exit 1
fi


export GITLAB_API_ENDPOINT=${endpoint}
export GITLAB_API_PRIVATE_TOKEN=${token}

# This one is optional and can be used to set any HTTParty option you
# may need
# using YAML hash syntax. For example, this is how you would disable
# SSL
# verification (useful if using a self-signed cert).
#export GITLAB_API_HTTPARTY_OPTIONS="{verify: false}"

gitlab $@
```

**Comment by timofonic** [comment]
@AAraKKe  @NARKOZ @cvand @asedge  What about this?

**Comment by logicminds** [comment]
Why have I never thought of this?  This makes a ton of sense.

**Comment by stevelacey** [comment]
I would argue whilst this is a neat addition you should support – it's probably pretty common to have >1 gitlab installations to care about – to that end, I actually chuck the credentials in the `.env` of my project and updated `gitlab-cli` to call `require('dotenv').config()` at the top – meaning I can use the right gitlab for the right project 👌

**Comment by strk** [comment]
@stevelacey how's that different from the proposed solution ? It'd be in `.git/config` instead of in `.env`, for each project. Of course I was talking about the _local_ git config, not the global one, you can see the code uses `git config`, not `git config -g`

**Comment by stevelacey** [comment]
@strk ignore me, it looks like I wasn't even commenting on the correct gitlab-cli project – and yes, of course, local config 👌

**Comment by NARKOZ** [comment]
Use environment variables to achieve this.

**Comment by strk** [comment]
NOTE: `Use environment variables` would NOT achieve what I was after. It would require me to keep changing my env variables everytime I move from one repository to another... I still think config in .git/config makes sense...
