### ISSUE TITLE
create project variables

### ISSUE THREAD

**Issue by logicminds** [NARKOZ/gitlab#333]
Please add the project variables call

https://docs.gitlab.com/ce/api/project_level_variables.html

Should this go in projects.rb or maybe a new file called variables.rb?

**Comment by timofonic** [comment]
@NARKOZ I understand your point of view. Anyway, what about guiding to a possible contributor about where to look and how it can be done?

**Comment by alexives** [comment]
Isn't this already implemented here: https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/build_variables.rb ?

**Comment by logicminds** [comment]
Oh sweet I was looking in the wrong place.
