### ISSUE TITLE
file_contents takes ID only, not ID or name as per doco

### ISSUE THREAD

**Issue by qume** [NARKOZ/gitlab#342]
In client/repository_files.rb, the various methods have documentation which say:

@param  [Integer, String] project The ID or name of a project.

Running this on the current gitlab release only works on ID, not name as far as I can tell.

If this is correct I'll update the documentation, but wanted to check first.

**Comment by asedge** [comment]
The project name must include the namespace, e.g. `foo/bar`.  Is that what you've tried?

**Comment by qume** [comment]
No I just used the repository name. Is this common knowledge that I missed or should perhaps that be mentioned in the documentation? I'm new to using this project.

**Comment by asedge** [comment]
If you look at the API docs you see references to the project path: https://docs.gitlab.com/ce/api/projects.html#get-single-project
