### ISSUE TITLE
No option to set read_timeout for calls

### ISSUE THREAD

**Issue by ilsinszkibal** [NARKOZ/gitlab#357]
When creating MRs we are experiencing Net::ReadTimeout. I didn't find an option to pass this option, if I am wrong, please correct me.

I am happy to submit an MR and would like to discuss the best direction to do so. Using the MergeRequests module's (merge_requests.rb file) create_merge_request method as an example, my suggestion is:

```    
def create_merge_request(project, title, body_options={}, options={})
      body_options = { title: title }.merge(body_options)
      options = options.merge( body: body_options)
      post("/projects/#{url_encode project}/merge_requests", options)
    end
```

An example call would look like:
```
get_client.create_merge_request(project, title, { source_branch:'develop', target_branch: 'master'}, {read_timeout: 180})
```

**Comment by neeraj-joshi01** [comment]
@ilsinszkibal Mind if I take this over?

**Comment by NARKOZ** [comment]
@neeraj-joshi01 sure, go ahead.

**Comment by neeraj-joshi01** [comment]
Have submitted the PR: #417
I have just added the timeout support for one particular function
Let me know if you want me to make it generic and for other different methods too

**Comment by NARKOZ** [comment]
You can set read timeout like this:

```rb
ENV['GITLAB_API_HTTPARTY_OPTIONS'] = "{read_timeout: 60}"
```
