### ISSUE TITLE
Homebrew install

### ISSUE THREAD

**Issue by frob** [NARKOZ/gitlab#361]
Add an install via homebrew.

I am not a ruby developer, I want to use this tool but I don't want to have to setup and maintain a ruby environment in order to use this tool. I don't use Ruby for anything else.

**Comment by criztovyl** [comment]
Maybe check if [brew-gem](https://github.com/sportngin/brew-gem) for installing gems via homebrew suits your needs. :)

**Comment by frob** [comment]
That worked, a proper homebrew formula would be nice, but this works. I have proposed adding this as an installation method in the readme.md #362

**Comment by frob** [comment]
That worked for me, but in #362 @NARKOZ stated that a real homebrew formula would be better. 

So how do we do that?

**Comment by NARKOZ** [comment]
I've submitted a PR to homebrew-core https://github.com/Homebrew/homebrew-core/pull/24421
