### ISSUE TITLE
Gitlab merge request endpoint (in Gitlab 9.5)

### ISSUE THREAD

**Issue by born4new** [NARKOZ/gitlab#371]
Hi there,

[That endpoint](https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests) is currently not implemented in [this tool](https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/merge_requests.rb#L4).

It'd be really cool to have it!

I can write the associated PR if needed.

Cheers!

**Comment by asedge** [comment]
A contribution would be welcome!

**Comment by born4new** [comment]
I'll give it a shot then 👍
