### ISSUE TITLE
Implement MR discussions endpoint

### ISSUE THREAD

**Issue by born4new** [NARKOZ/gitlab#381]
## Goal

Be able to manage [MR discussions](https://docs.gitlab.com/ee/api/discussions.html#create-new-merge-request-discussion)

## Motivation

I would like to have inline comments inside Gitlab MRs coming from the [danger gem](http://danger.systems/ruby/) (see [this issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/20700) on Gitlab's side)

That gem depends on [NARKOZ/gitlab](https://github.com/danger/danger-gitlab-gem/blob/master/danger-gitlab.gemspec#L17) (also see [that PR](https://github.com/danger/danger/issues/522))

So, in order to implement that feature in Danger, we'll first need to have it here :).

## Workforce

I can gladly do it: please let me know if you would be interested!

**Comment by NARKOZ** [comment]
Sure, PR is welcome!
