### ISSUE TITLE
Projects are not scoped on my user / using global Gitlab scope instead

### ISSUE THREAD

**Issue by bmedici** [NARKOZ/gitlab#387]
Hello,

I have a strange behaviour with this gem, when authenticating with my own key:
```
client = Gitlab.client(endpoint: 'https://gitlab.com/api/v4/', private_token: "XYZT" )
client.projects.collect(&:name)
```
returns random projects that are not mine at all:
```
=> ["rotwk202-source", "gitlab_taiga_integration", "TekSavvyProject", "TestProject", "acquire-frontend-exam", "gcp-is-awesome", "hello_prakash", "haskell-exercises", "webmail", "file2c", "node-js-sample1", "ZawayaLLC", "yara-system", "yara-project", "node-js-sample", "test", "GitLab CI Yml", "ewa", "digits", "Sis.Esc.BD"]
```
What could be the cause for his ?
How should I request all my projects or better, all my projects for a given Gitlab group ?
Thank you for your help !

**Comment by asedge** [comment]
Look at the method documentation for `#projects`, you can specify a `:scope` [here](https://github.com/NARKOZ/gitlab/blob/v4.4.0/lib/gitlab/client/projects.rb#L13).  This should limit it to a specific group.  The [API docs](https://docs.gitlab.com/ee/api/projects.html#list-all-projects) spell it out pretty simply:
> Get a list of all visible projects across GitLab for the authenticated user.

The other options specified in the API docs can be passed as part of an `options` Hash, which is the (optional) last argument of the `#projects` method call.
