### ISSUE TITLE
projects/:scope is deprecated on API v4 and scopes are now set on query parameters  

### ISSUE THREAD

**Issue by mwebler** [NARKOZ/gitlab#397]
Hi there 👋 
I was making calls to get a list of projects owned by the authenticated user, but I was getting a 404 error following the [example from the gem docs](https://www.rubydoc.info/gems/gitlab/Gitlab%2FClient%2FProjects:projects):
```ruby
client = Gitlab.client(endpoint: "https://gitlab.com/api/v4", private_token: access_token)
projects = lab.projects({scope: "owned"})
```

I looked into the [Gitlab API v4 docs](https://docs.gitlab.com/ce/api/projects.html#list-user-projects) and saw that `projects/:scope` was replaced by `owned`, `membership` and `starred` query parameters.

Indeed, the following query worked for me:
```ruby
projects = lab.projects({owned: true})
```

So, I think the IF clause that checks if there is a scope property can be removed from the `projects` method:
https://github.com/NARKOZ/gitlab/blob/b543f256c54be60a228346ba9f9932b62ffb6eba/lib/gitlab/client/projects.rb#L15-L21

And the docs can be updated to mention to use the new query parameters instead of the `scope`
https://github.com/NARKOZ/gitlab/blob/b543f256c54be60a228346ba9f9932b62ffb6eba/lib/gitlab/client/projects.rb#L13

If you agree with that I can submit a PR :)

**Comment by NARKOZ** [comment]
PR is welcome.
