### ISSUE TITLE
Find forked project by forked project ID

### ISSUE THREAD

**Issue by zedtux** [NARKOZ/gitlab#406]
Given I have already forked project with ID 1234, I would like to find my fork of the project with ID 1234, something like:

```ruby
forked_project = gitlab.fork_for_project(1234)
```

Is there anything already existing which could achieve that or should it has to be developed?

**Comment by NARKOZ** [comment]
You can use `project_forks` method.

See: https://github.com/NARKOZ/gitlab/blob/b141ed1a56c60314a315447f44c3e6f32fe2b146/lib/gitlab/client/projects.rb#L401-L417

**Comment by zedtux** [comment]
Thank you @NARKOZ for your answer, and I saw that one, but it will return me a long list of forked repo.
I would have to go through each forks, and search for the one which relates to the project ID ...

Actually this sounds like to be done on Gitlab side (no my project nor this library). I guess I should open an issue on GitLab side in order to get this implemented in their API so that you could add it in this library, right?

**Comment by NARKOZ** [comment]
>Actually this sounds like to be done on Gitlab side (no my project nor this library). I guess I should open an issue on GitLab side in order to get this implemented in their API so that you could add it in this library, right?

Yes.

**Comment by zedtux** [comment]
Here is the issue I have opened : https://gitlab.com/gitlab-org/gitlab-ce/issues/51038

**Comment by NARKOZ** [comment]
Thanks. Closing this then.

**Comment by zedtux** [comment]
Heum no, you'll have to implement it afterwards ... this should stay opened.
