### ISSUE TITLE
Missing endpoint for GET projects/:id/events

### ISSUE THREAD

**Issue by AnneshaChowdhury** [NARKOZ/gitlab#416]
* ```clients/event.rb ```has a bug for getting back the visible project events related to project IDs. 

```ruby
  def project_events(project, options = {})
    get("/#{url_encode project}/events", query: options)
  end
```
The ```projects``` keyword is missing before the ```/#{url_encode project}```

* I have worked that out, so maybe I can create a pull-request for the issue sometime soon?

**Comment by NARKOZ** [comment]
> * I have worked that out, so maybe I can create a pull-request for the issue sometime soon?

Yes, please.

**Comment by tudorpavel** [comment]
@NARKOZ PR submitted with this fix.

Happy Hacktoberfest!

**Comment by NARKOZ** [comment]
#418
