### ISSUE TITLE
Global namespace cluttering

### ISSUE THREAD

**Issue by glebglazov** [NARKOZ/gitlab#419]
Hey guys

Is Events module global now for some purpose or just a typo? Cause it's not really good to clutter app global namespace (esp. Rails apps with missing constants autoload)

Before:
https://github.com/NARKOZ/gitlab/blob/v4.5.0/lib/gitlab/client/events.rb#L1 

After:
https://github.com/NARKOZ/gitlab/blob/v4.6.0/lib/gitlab/client/events.rb#L5

**Comment by NARKOZ** [comment]
Thanks. Reverted in 3eec86493e1e824d5e1b27b7cc1b1f8135ddb536

Released in version 4.6.1

**Comment by glebglazov** [comment]
👍
