### ISSUE TITLE
Gitlab.session does not exist anymore, write hint in examples on ghpages

### ISSUE THREAD

**Issue by robstoll** [NARKOZ/gitlab#420]
I think the session API was removed in newer gitlab versions (I don't know since when). Thus I suggest you leave a note in the example here:
http://narkoz.github.io/gitlab/examples

**Comment by robstoll** [comment]
Sure about removing it? Older versions still have it and to some people this might be still valuable.

**Comment by NARKOZ** [comment]
We support only GitLab API v4.
