### ISSUE TITLE
File Templates

### ISSUE THREAD

**Issue by connorshea** [NARKOZ/gitlab#432]
The gem is missing methods for various file templates:
- [`Dockerfile` templates](https://docs.gitlab.com/ce/api/templates/dockerfiles.html)
- [`.gitignore` templates](https://docs.gitlab.com/ce/api/templates/gitignores.html)
- [`.gitlab-ci.yml` templates](https://docs.gitlab.com/ce/api/templates/gitlab_ci_ymls.html)
- [License templates](https://docs.gitlab.com/ce/api/templates/licenses.html) (see also #226?)

Interestingly, 11.5 (releasing November 2018) looks like it will add [Project templates](https://docs.gitlab.com/ce/api/project_templates.html), and also deprecate the above template APIs in favor of it.

🤷‍♂️

**Comment by akkee** [comment]
Sorry if I am missing something, how is the project template API going to deprecate these existing instance level templates' API. As far as I can see in the doc, the `project` argument is marked as `required`. Even the doc doesn't specify how.

**Comment by NARKOZ** [comment]
They mention that Project templates API is a project-specific version of these endpoints.
