### ISSUE TITLE
Http error 429

### ISSUE THREAD

**Issue by MarkGibbons** [NARKOZ/gitlab#458]
When rate limiting is turned on in gitlab and a 429 is returned the body is returned as text, not json.
An error "Gitlab::Error::Parsing: The response is not a valid JSON" is raised instead of a TooManyRequests Retry Later error.

I got this stack trace.
Gitlab::Error::Parsing: chef_cookbook[jenkins] (restaurant::cookbooks line 52) had an error: Gitlab::Error::Parsing: gitlab_hook[jenkins org webhook] (/var/chef/cache/cookbooks/restaurant/resources/chef_cookbook.rb line 136) had an error: Gitlab::Error::Parsing: The response is not a valid JSON
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.6.1/lib/gitlab/request.rb:40:in `rescue in decode'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.6.1/lib/gitlab/request.rb:36:in `decode'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.6.1/lib/gitlab/request.rb:18:in `parse'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.6.1/lib/gitlab/request.rb:12:in `block in <class:Request>'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/httparty-0.16.2/lib/httparty/request.rb:391:in `parse_response'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/httparty-0.16.2/lib/httparty/request.rb:359:in `block in handle_response'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/httparty-0.16.2/lib/httparty/response.rb:25:in `parsed_response'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.6.1/lib/gitlab/error.rb:43:in `build_error_message'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.6.1/lib/gitlab/error.rb:20:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.6.1/lib/gitlab/request.rb:68:in `exception'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.6.1/lib/gitlab/request.rb:68:in `raise'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.6.1/lib/gitlab/request.rb:68:in `validate'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.6.1/lib/gitlab/request.rb:47:in `block (2 levels) in <class:Request>'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.6.1/lib/gitlab/client/projects.rb:176:in `project_hooks'
/var/chef/cache/cookbooks/restaurant/resources/gitlab_hook.rb:54:in `project_hooks'

I can code around the problem by changing self.decode in request.rb and by adding a TooManyRequests assignment for a 429 error in request.rb and a TooManyRequests class in error.rb.

````ruby
    # Decodes a JSON response into Ruby object.
    def self.decode(response)
      response ? JSON.load(response) : {}
    rescue JSON::ParserError
      return { message: response } if response.class == String
      raise Error::Parsing, 'The response is not a valid JSON'
    end

   error_class = ...
                         when 429 then Error::TooManyRequests
                         ...
````ruby

A real solution would probably take into account the type of information in the body specified by the headers and changes in request parse routine and decode which both seem to assume they will be handed JSON in the body.

Thanks,
   Mark

**Comment by MarkGibbons** [comment]
Working on a PR.

**Comment by NARKOZ** [comment]
1cd2c28799941f6f9a3ff24015235645ddabe72f
