### ISSUE TITLE
Global Search

### ISSUE THREAD

**Issue by connorshea** [NARKOZ/gitlab#469]
Search methods exist for Projects and Groups, but not for the Global Search endpoints 

https://docs.gitlab.com/ce/api/search.html#global-search-api

**Comment by akkee** [comment]
If I am not wrong, existing methods for search are just top level searches for projects and groups by `name`. The ones mentioned here essentially searches by scope inside particular groups, particular projects or globally. We would need to build the wrapper for all these endpoints, as a separate `Search API` endpoint
