### ISSUE TITLE
Group Labels API

### ISSUE THREAD

**Issue by connorshea** [NARKOZ/gitlab#476]
This was just merged and will be included in 11.8 (February 22nd release): https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/21368

It adds support for Group Labels in the API: https://docs.gitlab.com/ce/api/group_labels.html

Endpoints include:

- List group labels
- Create a new group label
- Update a group label
- Delete a group label
- Subscribe to a group label
- Unsubscribe from a group label

**Comment by NARKOZ** [comment]
Added in 72b14fb
