### ISSUE TITLE
Gitlab.project_releases doesn't exist anymore

### ISSUE THREAD

**Issue by JurgenJocubeit** [NARKOZ/gitlab#479]
https://docs.gitlab.com/ce/api/releases/index.html

It's now available under /projects/:id/releases

**Comment by NARKOZ** [comment]
Do you get errors when using `.project_releases`? https://github.com/NARKOZ/gitlab/blob/1c1b490e29cb20ecaaac7aab9c70d910782b22d2/lib/gitlab/client/project_releases.rb#L7-L16

The endpoint is correct.

**Comment by JurgenJocubeit** [comment]
My apologies, it appears I was using v4.8.0, which didn't have the Releases and ReleaseLink updates.
