### ISSUE TITLE
ObjectifiedHash in a YAML pstore

### ISSUE THREAD

**Issue by bretweinraub** [NARKOZ/gitlab#504]
If you have a YAML backed pstore, you can write a GitLab group [as represented by a ObjectifiedHash] into it, but when you reload it, you will get:

NoMethodError: undefined method `keys' for nil:NilClass
	from ....../gems/gitlab-4.11.0/lib/gitlab/objectified_hash.rb:32:in `respond_to_missing?'

**Comment by NARKOZ** [comment]
Could you provide a minimal reproduction that demonstrates the problem?

**Comment by bretweinraub** [comment]
Yeah sorry, I don't have the code anymore.
