### ISSUE TITLE
failure gitlab upload_file

### ISSUE THREAD

**Issue by williamalvessantos** [NARKOZ/gitlab#510]
Dears,

I'm wanting to update a file for a project that has ID: 145

File Contents:

cat myfile 
Hello

Commando:

```
gitlab upload_file 145 myfile
Server responded with code 400, message: file is invalid. Request URI: http://gitlab.mydomain.com.br/api/v4/projects/145/uploads
```

A help can help me understand a failure.

Thankful

[VERSIONS]

**GitLab:**
- Version: 12.0.3-ee (1b1872f9d93)

**ruby --version:**
- ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

**gem -v:**
- 3.0.4

**gitlab --version:**
- Gitlab Ruby Gem 4.12.0

**Comment by williamalvessantos** [comment]
Others informations - GitLab Info:

GitLab Shell 9.3.0
GitLab Workhorse v8.7.0
GitLab API v4
Ruby 2.6.3p62
Rails 5.1.7

**Comment by akashdotsrivastava** [comment]
I can see why this must be happening. The `upload_file` api requires you to pass a file object as an argument, and not the file path as string. Now that is achievable easily when you are using this gem inside a ruby app or irb, using the example in the documentation, but when one needs to use it in a CLI, passing a file argument is for lack of a better word, tricky. Hence, the issue.

I have suggested a change to the API in #514 , where the argument passed is file full_path and the method will take care of converting it to a file object. If it gets merged, it might solve @williamalvessantos 's problem with the CLI.
