### ISSUE TITLE
Running `gitlab variables` won't return all variables

### ISSUE THREAD

**Issue by zilti** [NARKOZ/gitlab#525]
As the title says, running `gitlab variables <projectname>` will only return a handful of variables instead of all.

**Comment by zilti** [comment]
*shrug*

**Comment by NARKOZ** [comment]
Could you provide an example with expected and actual results?

**Comment by NARKOZ** [comment]
Closing this as the client only performs API calls and returns whatever the GitLab instance gives in response. 

If you're still facing the issue please provide more details so we can reproduce.
