### ISSUE TITLE
How to search for a username?

### ISSUE THREAD

**Issue by viktorsmari** [NARKOZ/gitlab#529]
I have the same issue as #201 and I am not sure how to pass it as an option.

I cannot find an example in the documentation.

Should this work?
`Gitlab.user_search({username:'someuser'})`

**Edit:** 
This works, but do we need the empty string?
`Gitlab.user_search('' , {username:'someuser'})`

**Comment by martijnbleeker** [comment]
A better option may be:

``` ruby
Gitlab.users(username: "someuser")
```
