### ISSUE TITLE
Adding spent time with negative values cause timelogs error

### ISSUE THREAD

**Issue by lucasm-iRonin** [NARKOZ/gitlab#538]
Gitlab API supports providing negative values to add spent time endpoint which allows to remove all or part of the already tracked time. Since `add_time_spent_on_issue` method uses `url_encode` on `duration` before sending it to Gitlab, it results in error. `-2m` is sent as `%2d2m` and it returns `'timelogs' is invalid` error from GitLab.

Is it really necessary to use `url_encode` for duration?

**Comment by NARKOZ** [comment]
It is a bug. PR is welcome.

**Comment by lowski** [comment]
> It is a bug. PR is welcome.

Thanks! Addressed in #539.
