### ISSUE TITLE
Is it possible to search for a user by email address?

### ISSUE THREAD

**Issue by viktorsmari** [NARKOZ/gitlab#545]
If this is how we search for a user by `username`:

```ruby
Gitlab.users(username: "someuser")
```

How can we search by user `email` address?

The Gitlab API [documentation](https://docs.gitlab.com/ee/api/users.html) says:
> You can also search for users by name or primary email using ?search=. For example. /users?search=John.

Does this gem support it?

Related to #529

**Comment by viktorsmari** [comment]
Found the answer after a lot of digging:
```ruby
Gitlab.users(search: 'email@test.com')
```
Would be nice that instead of `search` it would be `email` but I guess that is an issue with the Gitlab API?

Should we add this as an example to the documentation?

**Comment by NARKOZ** [comment]
PR is welcome.
