### ISSUE TITLE
[Feature Request] Flag to omit table drawing

### ISSUE THREAD

**Issue by forflo** [NARKOZ/gitlab#553]
# Problem

Quite often it is useful to take the outputs of the gitlab CLI command and use it in shell scripts. Currently this is not easily done, as gitlab always prints a ASCII table surrounding even single element result sets.

## Current state of the art

```
bash-5.0$ gitlab group fnord --only=id
+--------------------------------------+
| Gitlab.group fnord, --only=id        |
+--------------------------------------+
| id                                   |
+--------------------------------------+
| 220                                  |
+--------------------------------------+
```

## Feature request

Nice to have flag: `--no-table`

```
bash-5.0$ gitlab group personalorka --only=id --no-table
220
```

**Comment by asedge** [comment]
I'm pretty sure you can get JSON.

**Comment by agargiulo** [comment]
```
[13:44:49] % gitlab user foo --only=id --json
{
  "cmd": "Gitlab.user foo, --only=id",
  "result": {
    "id": 2
  }
}
```
Would be nice, however, if the documentation showed this in more than a passing comment on one or two examples

**Comment by forflo** [comment]
> I'm pretty sure you can get JSON.
> 
> Edit: Yup, use `--json`.

Nice. Thank you!
