### ISSUE TITLE
Is it possible to use endpoint without authentication

### ISSUE THREAD

**Issue by fstybel** [NARKOZ/gitlab#554]
I would use this gem for fetching information from endpoints without authentication.
For example [projects](https://docs.gitlab.com/ee/api/projects.html#get-single-project) endpoint don't require authentication. But the gem require it. 

```ruby
[20] pry(main)> Gitlab.project('gitlab-org%2Fgitlab')
Gitlab::Error::MissingCredentials: Please provide a private_token or auth_token for user
from /usr/local/bundle/gems/gitlab-3.6.1/lib/gitlab/request.rb:100:in `set_authorization_header'
[21] pry(main)> Gitlab.private_token = 'fake-token'
=> "fake-token"
[22] pry(main)> Gitlab.project('gitlab-org%2Fgitlab')
Gitlab::Error::Unauthorized: Server responded with code 401, message: 401 Unauthorized. Request URI: https://gitlab.com/api/v4/projects/gitlab-org%2Fgitlab
from /usr/local/bundle/gems/gitlab-3.6.1/lib/gitlab/request.rb:69:in `validate'
```

But the endpoint is public - https://gitlab.com/api/v4/projects/gitlab-org%2Fgitlab

**Comment by fist28** [comment]
At the latest version of gem I can use workaround to reach the goal.
```
Gitlab.get("/projects/gitlab-org%2Fgitlab", unauthenticated: true)
```
I think that it should be possibility to use method `#project` for example with flag `unauthenticated: true` to fetch data without authorization.

**Comment by YorickPeterse** [comment]
@fist28 You can set the private token to an empty string:

```ruby
Gitlab.endpoint = 'https://gitlab.com/api/v4'
Gitlab.private_token = ''
Gitlab.project('gitlab-org/gitlab').id # => 278964
```
