### ISSUE TITLE
command line lint .gitlab-ci.yml

### ISSUE THREAD

**Issue by liaden** [NARKOZ/gitlab#566]
It would be nice to be able to lint the yml from bash as a local git hook. We already have https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/client/lint.rb#L14-L17 but it is marked as hidden due to the regex at https://github.com/NARKOZ/gitlab/blob/13052e50e3f869129210ef116fbf4586dca45de5/lib/gitlab.rb#L45 due to the method name having `validate` in it.

**Comment by NARKOZ** [comment]
Thank you for the report. Version 4.16.0 was released with the fix.
