### ISSUE TITLE
delete source branch when issuing an MR

### ISSUE THREAD

**Issue by asherungar** [NARKOZ/gitlab#572]
Hi,

can you please add the option to select to delete the source branch once a merge is done to the CLI
gitlab create_merge_request

Thanks
Asher

**Comment by akashdotsrivastava** [comment]
Hi @asherungar , the option to set deletion of a source branch on merge, while creating MR is already available. The `options` hash can take any of the valid values included in the options showing up in https://docs.gitlab.com/ee/api/merge_requests.html#create-mr, including `remove_source_branch`. So you can set the same using something like this:

```sh
  gitlab create_merge_request 4 "New merge request" "{source_branch: 'new_branch', target_branch: 'master', remove_source_branch: true}"
```

Although, the same option and few others were missing from the documentation. I have added them in #573 . Please note that you do not need to wait for this documentation to get merged to use the option.
