### ISSUE TITLE
Commands docs is mising.

### ISSUE THREAD

**Issue by neboduus** [NARKOZ/gitlab#589]
[commands implemented in this gem docs](https://www.rubydoc.info/gems/gitlab/4.5.0/Gitlab/Client) are missing

**Comment by NARKOZ** [comment]
Sorry, I didn't get you. What do you mean?

**Comment by neboduus** [comment]
I didn t find any documentation which specifies the available commands for the CLI (not for the gem)

**Comment by AgoraSecurity** [comment]
+1

I can't find any online documentation (what methods are available, etc.)

**Comment by AgoraSecurity** [comment]
https://www.rubydoc.info/gems/gitlab/4.17.0/toplevel is now available :)

**Comment by nickylogan** [comment]
Am I drunk or is the documentation no longer available?

**Comment by NARKOZ** [comment]
This is an issue with RubyDoc.info
Please raise a ticket at https://github.com/docmeta/rubydoc.info/issues

Alternatively if you installed the gem with docs, you can browse the docs locally.
