### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by cortesoft** [NARKOZ/gitlab#590]
The links at the top of the readme to the documentation return 404s: https://www.rubydoc.info/gems/gitlab/frames

**Comment by hoijui** [comment]
duplicate of https://github.com/NARKOZ/gitlab/issues/590

**Comment by NARKOZ** [comment]
Works for me. Could you check again, please?

**Comment by hoijui** [comment]
ahh yep, works again now! :-)

**Comment by NARKOZ** [comment]
Great 🥳
