### ISSUE TITLE
dependency on httparty to be bumped to >= 0.18 because of tests?

### ISSUE THREAD

**Issue by boutil** [NARKOZ/gitlab#591]
Hi,

The following change 
https://github.com/NARKOZ/gitlab/commit/46343c91940df46d773e564
is not needed for httparty 0.17.3, and results in test failures with httparty 0.17.3 and earlier. However, it is needed for tests to pass with httparty 0.18.

Maybe it is better to indicate that the minimal version for httparty is 0.18 and not 0.14?

Thanks

P.S.: this is related to a Debian bug where httparty 0.18 is causing test regression with gitlab 4.14.1.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=974093

**Comment by NARKOZ** [comment]
Thank you. Fixed in 87ff403 and version 4.17.0 was released which includes this fix.
