### ISSUE TITLE
Official Ruby 3.0 support

### ISSUE THREAD

**Issue by tnir** [NARKOZ/gitlab#611]
All rspecs are not successful in Ruby 3.0 environment as seen in https://github.com/NARKOZ/gitlab/runs/1698033311 (tested 2 months ago).

Is there any plan and/or update?

**Comment by tnir** [comment]
Will be done in #598.

**Comment by NARKOZ** [comment]
The next released version will come with official Ruby 3.0 support.

 9898f1c

**Comment by tnir** [comment]
Thanks!
