### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by abeger** [NARKOZ/gitlab#612]
https://www.rubydoc.info/gems/gitlab/frames is returning a 404. Tried with [other](https://www.rubydoc.info/gems/gitlab/4.16.1) [versions](https://www.rubydoc.info/gems/gitlab/4.14.1), too, and got the same problem.

**Comment by wiebersk** [comment]
I noticed this too and found it at https://rubydoc.info/github/NARKOZ/gitlab which works for me now. I'm unsure why the normal gem doc URL isn't working.

**Comment by NARKOZ** [comment]
Duplicate of #589
