### ISSUE TITLE
Please build gitlab against terminal-table >= 3.0.1

### ISSUE THREAD

**Issue by dbro86** [NARKOZ/gitlab#616]
Please build gitlab against terminal-table >= 3.0.1

Kind regards
Brody

**Comment by NARKOZ** [comment]
New version will be released next week with the fix #613 included.

**Comment by dbro86** [comment]
I would like to ask for the release?

**Comment by dbro86** [comment]
Is there any plan to release the fix?

**Comment by emmahsax** [comment]
@NARKOZ I'll +1 to releasing a new release with these changes. Very nice!

@dbro86 In the meantime, we can pull directly from GitHub:
```ruby
gem 'gitlab', 'git: 'https://github.com/NARKOZ/gitlab'
```

**Comment by theflow** [comment]
another friendly ping to release a new version 🙏

**Comment by Rarian** [comment]
Just another vote to release this version, if possible.  Thanks!

**Comment by NARKOZ** [comment]
I've just released a new version and pushed to Rubygems https://github.com/NARKOZ/gitlab/releases/tag/v4.18.0

Sorry for the wait!
