### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by andrcuns** [NARKOZ/gitlab#632]
It has been a year since last version was released.

Main branch contains quite a few new changes for gitlab v14+. Not having these changes is blocking quite a few projects depending on this gem.

Could You please release a new version with latest changes?

**Comment by andre-alves** [comment]
Would love to see a new version as well, as I need to use impersonation_token API.

**Comment by NARKOZ** [comment]
I've just released a new version and pushed to Rubygems https://github.com/NARKOZ/gitlab/releases/tag/v4.18.0

Sorry for the wait!

**Comment by andrcuns** [comment]
Awesome, thanks a lot 🎉
