### ISSUE TITLE
Automate gem releases

### ISSUE THREAD

**Issue by renehernandez** [NARKOZ/gitlab#644]
As the title said, it is an idea worth consider automating the releases of new gem versions

### Benefits
- Faster access of the latest improvements and features for gem users
- Elimination of issues asking for creation of new releases
- Potentially making it easier to compare when a problem what introduced across different versions of gitlab gems

### Potential approaches

- [semantic-release](https://semantic-release.gitbook.io/semantic-release/)

**Comment by garaujodev** [comment]
I saw that the mentioned approach have the necessity to standard all commit messages prefix, and this could be a problem whether it's an open source project (Ok, we have tools to enforce valid commit messages, but I think that is not worth).
