### ISSUE TITLE
Would we like to include GraphQL API capabilities?

### ISSUE THREAD

**Issue by ltickett** [NARKOZ/gitlab#659]
Has there been any conversation around adding support for GraphQL to the Gem?

I realise it is quite a different beast to the REST API, but there are definitely a number of implementations of a GraphQL client consuming the GitLab API in Ruby, and it would be great to try and build something reusable.

Thanks

**Comment by NARKOZ** [comment]
Definitely this is something that I'd like to implement as well as rewrite the client, but it requires some time dedication which unfortunately I can't allow for now.

**Comment by ltickett** [comment]
That's great to hear. I'm sure the GitLab team and community would be happy to try and support/collaobrate/contribute.

Let us know how we might be able to help 💙

**Comment by chino** [comment]
+1 for this

I was wondering might be nice to make it easy to share the connection setup code with this gem if planning to use them together:

https://github.com/github/graphql-client#configuration


@ticket any good gems you recommend from your research?

**Comment by ltickett** [comment]
> +1 for this
> 
> @ltickett any good gems you recommend from your research?

Sorry I missed this.

I think https://github.com/github/graphql-client is the only one i've used.

However, I must admit I've found myself falling back to hand crafting using HTTParty (I suspect that's because i'm more technical and know exactly what's what).

The beauty of the gem is that it uses introspection to grab the GraphQL schema and can then validate/verify a query locally. Then again, this query/response is quite large and unless cached would probably introduce significant delays/perofmrnace challenges. I don't believe it has any pagination handling etc either (this is something I expected to get).

What might be a good way to start brainstorming?

I will reach out to some team mates to see if they have any ideas/suggestions? Perhaps we could also find some other GraphQL API's with Ruby gems/wrappers and see how they approached it?

Thanks
