### ISSUE TITLE
EOFError: end of file reached on groups API

### ISSUE THREAD

**Issue by amitmahajan12** [NARKOZ/gitlab#682]
I am running into this error when calling the `groups` API. The request is make with a private token for a self hosted client. I'd appreciate if you can help me with it or point me in the right direction.

```
EOFError: end of file reached
from /usr/local/lib/ruby/2.7.0/net/protocol.rb:225:in `rbuf_fill'
```

**Comment by jnbohrer** [comment]
Calling the API endpoint via curl returns an empty list (`[]`). Could this be an issue with handling an edge case of 0 groups?
