### ISSUE TITLE
How to create Incident?

### ISSUE THREAD

**Issue by ytiruces** [NARKOZ/gitlab#691]
Hi. How to create Incident?
I think something like this:
`Gitlab.create_issue(5, 'New issue', { description: 'This is a new issue', assignee_id: 42, type: Incedent })` ?
I can't find it in docs.

**Comment by ltickett** [comment]
Hey @ytiruces try:

```
Gitlab.create_issue(5, 'New issue', { description: 'This is a new issue', assignee_id: 42, issue_type: 'incident' })
```

See: https://docs.gitlab.com/ee/api/issues.html#new-issue
