### ISSUE TITLE
API Error: 404 API Version Not Found when Accessing Commits and Files via python-gitlab

### ISSUE THREAD

**Issue by yangxi628** [NARKOZ/gitlab#703]
Hello,

I am encountering a 404 API Version Not Found error while attempting to access commit history and file contents using the python-gitlab library, even though I have explicitly set the API version to v4. The error occurs when I try to retrieve commits or files for a specific project. the file has been removed from repo but i think i can still get the file from commit

Steps to Reproduce:
Initialize python-gitlab with api_version='4' and a valid private token.
Attempt to retrieve commit history or file content using project.commits.list() or project.files.get().
Encounter the 404 API Version Not Found error.

Code Sample:
import gitlab

gl = gitlab.Gitlab('https://gitlab.comt', private_token='your_private_token', api_version='4')
project = gl.projects.get('11111')
commits = project.commits.list(path='path/to/deleted/file', all=True)

Error:
gitlab.exceptions.GitlabListError: 404: API Version Not Found

**Comment by NARKOZ** [comment]
This repository is for the **ruby** gitlab library.
