### ISSUE TITLE
delete project hook 

### ISSUE THREAD

**Issue by zlx** [NARKOZ/gitlab#75]
raise "Couldn't parse a response body" when I call delete_project_hook with an invalid hook_id, eg:

```ruby
client = Gitlab.client
client.delete_project_hook(project_id, hook_id)  # hook_id is deleted, raise Couldn't parse a response body
```

And I find an discription via https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/projects.md#delete-project-hook
> Note the JSON response differs if the hook is available or not. If the project hook is available before it is returned in the JSON response or an empty response is returned.

maybe we have not handle it differently.

**Comment by MichaelSp** [comment]
I just came across this. 
So +1 here
