### ISSUE TITLE
Return error message  more explicit

### ISSUE THREAD

**Issue by camlafit** [NARKOZ/gitlab#99]
Hi

Follow #98 issue, I open a new to help to follow problem.

On some case for example with this command :
`gitlab create_user "cam@example.com" "tototo" "{username: camlafit, name: 'cam'}"`

Return this result : 
`
Server responded with code 400, message: #<Gitlab::ObjectifiedHash:0x000000013353f0>. Request URI: https://example.com/api/v3/users`

Problem is in fact a password not enough strong. With a password stronger, result is ok.

**Comment by asedge** [comment]
The error responses for user creation are inconsistent.  Consider the following two examples for trying to create a user via the API.

This response is just a String:
```
$ ./bin/gitlab create_user "cam@example.com" "tototo" "{name: 'cam'}"
"400 (Bad request) \"username\" not given"
```

This error response is JSON so the gem converts it to an ObjectifiedHash:
```
$ ./bin/gitlab create_user "cam@example.com" "tototo" "{username: camlafit, name: 'cam', projects_limit: -1}"
#<Gitlab::ObjectifiedHash:0x00000002aaf2b0 @hash={"password"=>["is too short (minimum is 8 characters)"], "projects_limit"=>["must be greater than or equal to 0"]}, @data={"password"=>["is too short (minimum is 8 characters)"], "projects_limit"=>["must be greater than or equal to 0"]}>
```

I have some code that will handle the ObjectifiedHash case but it doesn't feel like the right thing to do here.  It should probably be fixed in Gitlab instead.  @NARKOZ Do you have any thoughts on this?

**Comment by camlafit** [comment]
Is not possible to check type on any response and convert only if is act as a json format ?

**Comment by asedge** [comment]
As I said, I have code that works for this scenario.  I'm just asking the question "does it make sense to work around this or should it be something that gets changed in Gitlab itself?".

**Comment by NARKOZ** [comment]
We should check for response code `400` and `message` property in returned JSON. If it exists, output message contents (string or array).


Ideally GitLab API should return error details in format:

```
{
   "message": "Validation Failed",
   "errors": [
     {
       "resource": "Issue",
       "field": "title",
       "message": "Missing field"
     }
   ]
 }
```

so you could iterate over errors, unlike current approach 
https://github.com/gitlabhq/gitlabhq/tree/master/doc/api#data-validation-and-error-reporting

**Comment by asedge** [comment]
> https://github.com/gitlabhq/gitlabhq/tree/master/doc/api#data-validation-and-error-reporting

Wow, I can't believe I didn't see this. :frowning:
